/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AddressModel  {
  
  @SerializedName("country_id")
  private String countryId = null;
  @SerializedName("country_name")
  private String countryName = null;
  @SerializedName("post_code")
  private String postCode = null;
  @SerializedName("province_id")
  private String provinceId = null;
  @SerializedName("province_name")
  private String provinceName = null;
  @SerializedName("city_id")
  private String cityId = null;
  @SerializedName("city_name")
  private String cityName = null;
  @SerializedName("district_id")
  private String districtId = null;
  @SerializedName("district_name")
  private String districtName = null;
  @SerializedName("detailed_address")
  private String detailedAddress = null;
  @SerializedName("realname")
  private String realname = null;
  @SerializedName("phone_number")
  private String phoneNumber = null;
  @SerializedName("mail")
  private String mail = null;

  /**
   * 国家ID
   **/
  @ApiModelProperty(value = "国家ID")
  public String getCountryId() {
    return countryId;
  }
  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  /**
   * 国家名称
   **/
  @ApiModelProperty(value = "国家名称")
  public String getCountryName() {
    return countryName;
  }
  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  /**
   * 邮编
   **/
  @ApiModelProperty(value = "邮编")
  public String getPostCode() {
    return postCode;
  }
  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  /**
   * 省份ID
   **/
  @ApiModelProperty(value = "省份ID")
  public String getProvinceId() {
    return provinceId;
  }
  public void setProvinceId(String provinceId) {
    this.provinceId = provinceId;
  }

  /**
   * 省份名称
   **/
  @ApiModelProperty(value = "省份名称")
  public String getProvinceName() {
    return provinceName;
  }
  public void setProvinceName(String provinceName) {
    this.provinceName = provinceName;
  }

  /**
   * 城市ID
   **/
  @ApiModelProperty(value = "城市ID")
  public String getCityId() {
    return cityId;
  }
  public void setCityId(String cityId) {
    this.cityId = cityId;
  }

  /**
   * 城市名称
   **/
  @ApiModelProperty(value = "城市名称")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   * 区ID
   **/
  @ApiModelProperty(value = "区ID")
  public String getDistrictId() {
    return districtId;
  }
  public void setDistrictId(String districtId) {
    this.districtId = districtId;
  }

  /**
   * 区名
   **/
  @ApiModelProperty(value = "区名")
  public String getDistrictName() {
    return districtName;
  }
  public void setDistrictName(String districtName) {
    this.districtName = districtName;
  }

  /**
   * 详细地址
   **/
  @ApiModelProperty(value = "详细地址")
  public String getDetailedAddress() {
    return detailedAddress;
  }
  public void setDetailedAddress(String detailedAddress) {
    this.detailedAddress = detailedAddress;
  }

  /**
   * 姓名
   **/
  @ApiModelProperty(value = "姓名")
  public String getRealname() {
    return realname;
  }
  public void setRealname(String realname) {
    this.realname = realname;
  }

  /**
   * 电话号码
   **/
  @ApiModelProperty(value = "电话号码")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * 邮件地址
   **/
  @ApiModelProperty(value = "邮件地址")
  public String getMail() {
    return mail;
  }
  public void setMail(String mail) {
    this.mail = mail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressModel addressModel = (AddressModel) o;
    return (countryId == null ? addressModel.countryId == null : countryId.equals(addressModel.countryId)) &&
        (countryName == null ? addressModel.countryName == null : countryName.equals(addressModel.countryName)) &&
        (postCode == null ? addressModel.postCode == null : postCode.equals(addressModel.postCode)) &&
        (provinceId == null ? addressModel.provinceId == null : provinceId.equals(addressModel.provinceId)) &&
        (provinceName == null ? addressModel.provinceName == null : provinceName.equals(addressModel.provinceName)) &&
        (cityId == null ? addressModel.cityId == null : cityId.equals(addressModel.cityId)) &&
        (cityName == null ? addressModel.cityName == null : cityName.equals(addressModel.cityName)) &&
        (districtId == null ? addressModel.districtId == null : districtId.equals(addressModel.districtId)) &&
        (districtName == null ? addressModel.districtName == null : districtName.equals(addressModel.districtName)) &&
        (detailedAddress == null ? addressModel.detailedAddress == null : detailedAddress.equals(addressModel.detailedAddress)) &&
        (realname == null ? addressModel.realname == null : realname.equals(addressModel.realname)) &&
        (phoneNumber == null ? addressModel.phoneNumber == null : phoneNumber.equals(addressModel.phoneNumber)) &&
        (mail == null ? addressModel.mail == null : mail.equals(addressModel.mail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (countryId == null ? 0: countryId.hashCode());
    result = 31 * result + (countryName == null ? 0: countryName.hashCode());
    result = 31 * result + (postCode == null ? 0: postCode.hashCode());
    result = 31 * result + (provinceId == null ? 0: provinceId.hashCode());
    result = 31 * result + (provinceName == null ? 0: provinceName.hashCode());
    result = 31 * result + (cityId == null ? 0: cityId.hashCode());
    result = 31 * result + (cityName == null ? 0: cityName.hashCode());
    result = 31 * result + (districtId == null ? 0: districtId.hashCode());
    result = 31 * result + (districtName == null ? 0: districtName.hashCode());
    result = 31 * result + (detailedAddress == null ? 0: detailedAddress.hashCode());
    result = 31 * result + (realname == null ? 0: realname.hashCode());
    result = 31 * result + (phoneNumber == null ? 0: phoneNumber.hashCode());
    result = 31 * result + (mail == null ? 0: mail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressModel {\n");
    
    sb.append("  countryId: ").append(countryId).append("\n");
    sb.append("  countryName: ").append(countryName).append("\n");
    sb.append("  postCode: ").append(postCode).append("\n");
    sb.append("  provinceId: ").append(provinceId).append("\n");
    sb.append("  provinceName: ").append(provinceName).append("\n");
    sb.append("  cityId: ").append(cityId).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  districtId: ").append(districtId).append("\n");
    sb.append("  districtName: ").append(districtName).append("\n");
    sb.append("  detailedAddress: ").append(detailedAddress).append("\n");
    sb.append("  realname: ").append(realname).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  mail: ").append(mail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
