/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.5接口 
 *
 * OpenAPI spec version: 1.4 build20170919-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AppTextWidgetStyleModel  {
  
  @SerializedName("font-family")
  private String fontFamily = null;
  @SerializedName("font-size")
  private String fontSize = null;
  @SerializedName("color")
  private String color = null;

  /**
   * 字体
   **/
  @ApiModelProperty(value = "字体")
  public String getFontFamily() {
    return fontFamily;
  }
  public void setFontFamily(String fontFamily) {
    this.fontFamily = fontFamily;
  }

  /**
   * 字号 单位像素
   **/
  @ApiModelProperty(value = "字号 单位像素")
  public String getFontSize() {
    return fontSize;
  }
  public void setFontSize(String fontSize) {
    this.fontSize = fontSize;
  }

  /**
   * 颜色16进制代码
   **/
  @ApiModelProperty(value = "颜色16进制代码")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppTextWidgetStyleModel appTextWidgetStyleModel = (AppTextWidgetStyleModel) o;
    return (fontFamily == null ? appTextWidgetStyleModel.fontFamily == null : fontFamily.equals(appTextWidgetStyleModel.fontFamily)) &&
        (fontSize == null ? appTextWidgetStyleModel.fontSize == null : fontSize.equals(appTextWidgetStyleModel.fontSize)) &&
        (color == null ? appTextWidgetStyleModel.color == null : color.equals(appTextWidgetStyleModel.color));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (fontFamily == null ? 0: fontFamily.hashCode());
    result = 31 * result + (fontSize == null ? 0: fontSize.hashCode());
    result = 31 * result + (color == null ? 0: color.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppTextWidgetStyleModel {\n");
    
    sb.append("  fontFamily: ").append(fontFamily).append("\n");
    sb.append("  fontSize: ").append(fontSize).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
