/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class AppWidgetModel  {
  
  @SerializedName("style_id")
  private String styleId = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("widget_id")
  private String widgetId = null;

  /**
   * 风格ID
   **/
  @ApiModelProperty(value = "风格ID")
  public String getStyleId() {
    return styleId;
  }
  public void setStyleId(String styleId) {
    this.styleId = styleId;
  }

  /**
   * 标题文字
   **/
  @ApiModelProperty(value = "标题文字")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 控件ID - deal_nav_{category_id}：优惠分类ID deal_nav_activity:优惠分类导航栏活动入口ID tab_deal:优惠TABID tab_discover:发现TABID tab_forum:论坛TABID tab_msgs:消息TABID tab_mine:我的TABID tab_activity:活动TABID deal_index_signing:每日签到入口ID deal_index_stores:返利商家入口ID deal_index_transshippers:转运物流入口ID deal_index_inviting:邀请好友入口ID
   **/
  @ApiModelProperty(value = "控件ID - deal_nav_{category_id}：优惠分类ID deal_nav_activity:优惠分类导航栏活动入口ID tab_deal:优惠TABID tab_discover:发现TABID tab_forum:论坛TABID tab_msgs:消息TABID tab_mine:我的TABID tab_activity:活动TABID deal_index_signing:每日签到入口ID deal_index_stores:返利商家入口ID deal_index_transshippers:转运物流入口ID deal_index_inviting:邀请好友入口ID")
  public String getWidgetId() {
    return widgetId;
  }
  public void setWidgetId(String widgetId) {
    this.widgetId = widgetId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppWidgetModel appWidgetModel = (AppWidgetModel) o;
    return (styleId == null ? appWidgetModel.styleId == null : styleId.equals(appWidgetModel.styleId)) &&
        (title == null ? appWidgetModel.title == null : title.equals(appWidgetModel.title)) &&
        (widgetId == null ? appWidgetModel.widgetId == null : widgetId.equals(appWidgetModel.widgetId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (styleId == null ? 0: styleId.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (widgetId == null ? 0: widgetId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppWidgetModel {\n");
    
    sb.append("  styleId: ").append(styleId).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  widgetId: ").append(widgetId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
