/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ChatMsgModel  {
  
  @SerializedName("msg_id")
  private String msgId = null;
  @SerializedName("msg")
  private String msg = null;
  @SerializedName("sender_uid")
  private String senderUid = null;
  @SerializedName("sender_name")
  private String senderName = null;
  @SerializedName("sender_avatar")
  private String senderAvatar = null;
  @SerializedName("is_me")
  private String isMe = null;
  @SerializedName("sent_time")
  private String sentTime = null;
  @SerializedName("sent_timestamp")
  private String sentTimestamp = null;

  /**
   * 消息ID
   **/
  @ApiModelProperty(value = "消息ID")
  public String getMsgId() {
    return msgId;
  }
  public void setMsgId(String msgId) {
    this.msgId = msgId;
  }

  /**
   * 消息内容
   **/
  @ApiModelProperty(value = "消息内容")
  public String getMsg() {
    return msg;
  }
  public void setMsg(String msg) {
    this.msg = msg;
  }

  /**
   * 发送者UID
   **/
  @ApiModelProperty(value = "发送者UID")
  public String getSenderUid() {
    return senderUid;
  }
  public void setSenderUid(String senderUid) {
    this.senderUid = senderUid;
  }

  /**
   * 发送者名字
   **/
  @ApiModelProperty(value = "发送者名字")
  public String getSenderName() {
    return senderName;
  }
  public void setSenderName(String senderName) {
    this.senderName = senderName;
  }

  /**
   * 发送者头像
   **/
  @ApiModelProperty(value = "发送者头像")
  public String getSenderAvatar() {
    return senderAvatar;
  }
  public void setSenderAvatar(String senderAvatar) {
    this.senderAvatar = senderAvatar;
  }

  /**
   * 是否是本人
   **/
  @ApiModelProperty(value = "是否是本人")
  public String getIsMe() {
    return isMe;
  }
  public void setIsMe(String isMe) {
    this.isMe = isMe;
  }

  /**
   * 发送时间
   **/
  @ApiModelProperty(value = "发送时间")
  public String getSentTime() {
    return sentTime;
  }
  public void setSentTime(String sentTime) {
    this.sentTime = sentTime;
  }

  /**
   * 时间戳
   **/
  @ApiModelProperty(value = "时间戳")
  public String getSentTimestamp() {
    return sentTimestamp;
  }
  public void setSentTimestamp(String sentTimestamp) {
    this.sentTimestamp = sentTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatMsgModel chatMsgModel = (ChatMsgModel) o;
    return (msgId == null ? chatMsgModel.msgId == null : msgId.equals(chatMsgModel.msgId)) &&
        (msg == null ? chatMsgModel.msg == null : msg.equals(chatMsgModel.msg)) &&
        (senderUid == null ? chatMsgModel.senderUid == null : senderUid.equals(chatMsgModel.senderUid)) &&
        (senderName == null ? chatMsgModel.senderName == null : senderName.equals(chatMsgModel.senderName)) &&
        (senderAvatar == null ? chatMsgModel.senderAvatar == null : senderAvatar.equals(chatMsgModel.senderAvatar)) &&
        (isMe == null ? chatMsgModel.isMe == null : isMe.equals(chatMsgModel.isMe)) &&
        (sentTime == null ? chatMsgModel.sentTime == null : sentTime.equals(chatMsgModel.sentTime)) &&
        (sentTimestamp == null ? chatMsgModel.sentTimestamp == null : sentTimestamp.equals(chatMsgModel.sentTimestamp));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (msgId == null ? 0: msgId.hashCode());
    result = 31 * result + (msg == null ? 0: msg.hashCode());
    result = 31 * result + (senderUid == null ? 0: senderUid.hashCode());
    result = 31 * result + (senderName == null ? 0: senderName.hashCode());
    result = 31 * result + (senderAvatar == null ? 0: senderAvatar.hashCode());
    result = 31 * result + (isMe == null ? 0: isMe.hashCode());
    result = 31 * result + (sentTime == null ? 0: sentTime.hashCode());
    result = 31 * result + (sentTimestamp == null ? 0: sentTimestamp.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatMsgModel {\n");
    
    sb.append("  msgId: ").append(msgId).append("\n");
    sb.append("  msg: ").append(msg).append("\n");
    sb.append("  senderUid: ").append(senderUid).append("\n");
    sb.append("  senderName: ").append(senderName).append("\n");
    sb.append("  senderAvatar: ").append(senderAvatar).append("\n");
    sb.append("  isMe: ").append(isMe).append("\n");
    sb.append("  sentTime: ").append(sentTime).append("\n");
    sb.append("  sentTimestamp: ").append(sentTimestamp).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
