/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.5接口 
 *
 * OpenAPI spec version: 1.4 build20170928-4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CollectionTransshipperModel  {
  
  @SerializedName("transshipper_id")
  private String transshipperId = null;
  @SerializedName("transshipper_name")
  private String transshipperName = null;
  @SerializedName("transshipper_logo")
  private String transshipperLogo = null;
  @SerializedName("points")
  private String points = null;
  @SerializedName("board_id")
  private String boardId = null;
  @SerializedName("comments_count")
  private String commentsCount = null;
  @SerializedName("collection_count")
  private String collectionCount = null;

  /**
   * 转运公司ID
   **/
  @ApiModelProperty(value = "转运公司ID")
  public String getTransshipperId() {
    return transshipperId;
  }
  public void setTransshipperId(String transshipperId) {
    this.transshipperId = transshipperId;
  }

  /**
   * 转运公司名称
   **/
  @ApiModelProperty(value = "转运公司名称")
  public String getTransshipperName() {
    return transshipperName;
  }
  public void setTransshipperName(String transshipperName) {
    this.transshipperName = transshipperName;
  }

  /**
   * 转运公司LOGO
   **/
  @ApiModelProperty(value = "转运公司LOGO")
  public String getTransshipperLogo() {
    return transshipperLogo;
  }
  public void setTransshipperLogo(String transshipperLogo) {
    this.transshipperLogo = transshipperLogo;
  }

  /**
   * 评分分数 即几颗星 为小数位为1位的实型
   **/
  @ApiModelProperty(value = "评分分数 即几颗星 为小数位为1位的实型")
  public String getPoints() {
    return points;
  }
  public void setPoints(String points) {
    this.points = points;
  }

  /**
   * 转运公司的论坛版块ID
   **/
  @ApiModelProperty(value = "转运公司的论坛版块ID")
  public String getBoardId() {
    return boardId;
  }
  public void setBoardId(String boardId) {
    this.boardId = boardId;
  }

  /**
   * 评论数
   **/
  @ApiModelProperty(value = "评论数")
  public String getCommentsCount() {
    return commentsCount;
  }
  public void setCommentsCount(String commentsCount) {
    this.commentsCount = commentsCount;
  }

  /**
   * 收藏数
   **/
  @ApiModelProperty(value = "收藏数")
  public String getCollectionCount() {
    return collectionCount;
  }
  public void setCollectionCount(String collectionCount) {
    this.collectionCount = collectionCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectionTransshipperModel collectionTransshipperModel = (CollectionTransshipperModel) o;
    return (transshipperId == null ? collectionTransshipperModel.transshipperId == null : transshipperId.equals(collectionTransshipperModel.transshipperId)) &&
        (transshipperName == null ? collectionTransshipperModel.transshipperName == null : transshipperName.equals(collectionTransshipperModel.transshipperName)) &&
        (transshipperLogo == null ? collectionTransshipperModel.transshipperLogo == null : transshipperLogo.equals(collectionTransshipperModel.transshipperLogo)) &&
        (points == null ? collectionTransshipperModel.points == null : points.equals(collectionTransshipperModel.points)) &&
        (boardId == null ? collectionTransshipperModel.boardId == null : boardId.equals(collectionTransshipperModel.boardId)) &&
        (commentsCount == null ? collectionTransshipperModel.commentsCount == null : commentsCount.equals(collectionTransshipperModel.commentsCount)) &&
        (collectionCount == null ? collectionTransshipperModel.collectionCount == null : collectionCount.equals(collectionTransshipperModel.collectionCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (transshipperId == null ? 0: transshipperId.hashCode());
    result = 31 * result + (transshipperName == null ? 0: transshipperName.hashCode());
    result = 31 * result + (transshipperLogo == null ? 0: transshipperLogo.hashCode());
    result = 31 * result + (points == null ? 0: points.hashCode());
    result = 31 * result + (boardId == null ? 0: boardId.hashCode());
    result = 31 * result + (commentsCount == null ? 0: commentsCount.hashCode());
    result = 31 * result + (collectionCount == null ? 0: collectionCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionTransshipperModel {\n");
    
    sb.append("  transshipperId: ").append(transshipperId).append("\n");
    sb.append("  transshipperName: ").append(transshipperName).append("\n");
    sb.append("  transshipperLogo: ").append(transshipperLogo).append("\n");
    sb.append("  points: ").append(points).append("\n");
    sb.append("  boardId: ").append(boardId).append("\n");
    sb.append("  commentsCount: ").append(commentsCount).append("\n");
    sb.append("  collectionCount: ").append(collectionCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
