/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CommentReplyModel  {
  
  @SerializedName("comment_id")
  private String commentId = null;
  @SerializedName("author")
  private String author = null;
  @SerializedName("authorid")
  private String authorid = null;
  @SerializedName("source")
  private String source = null;
  @SerializedName("comment")
  private String comment = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("author_groupname")
  private String authorGroupname = null;
  @SerializedName("author_level")
  private String authorLevel = null;
  @SerializedName("author_sex")
  private String authorSex = null;
  @SerializedName("postdate")
  private String postdate = null;
  @SerializedName("praise_count")
  private String praiseCount = null;
  @SerializedName("is_praised")
  private String isPraised = null;
  @SerializedName("is_sub_reply")
  private String isSubReply = null;
  @SerializedName("reply_username")
  private String replyUsername = null;

  /**
   * 评论ID
   **/
  @ApiModelProperty(value = "评论ID")
  public String getCommentId() {
    return commentId;
  }
  public void setCommentId(String commentId) {
    this.commentId = commentId;
  }

  /**
   * 评论人
   **/
  @ApiModelProperty(value = "评论人")
  public String getAuthor() {
    return author;
  }
  public void setAuthor(String author) {
    this.author = author;
  }

  /**
   * 评论人id
   **/
  @ApiModelProperty(value = "评论人id")
  public String getAuthorid() {
    return authorid;
  }
  public void setAuthorid(String authorid) {
    this.authorid = authorid;
  }

  /**
   * 来源（来自xxx）
   **/
  @ApiModelProperty(value = "来源（来自xxx）")
  public String getSource() {
    return source;
  }
  public void setSource(String source) {
    this.source = source;
  }

  /**
   * 评论内容
   **/
  @ApiModelProperty(value = "评论内容")
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * 评论人头像
   **/
  @ApiModelProperty(value = "评论人头像")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * 评论人用户组
   **/
  @ApiModelProperty(value = "评论人用户组")
  public String getAuthorGroupname() {
    return authorGroupname;
  }
  public void setAuthorGroupname(String authorGroupname) {
    this.authorGroupname = authorGroupname;
  }

  /**
   * 评论人等级
   **/
  @ApiModelProperty(value = "评论人等级")
  public String getAuthorLevel() {
    return authorLevel;
  }
  public void setAuthorLevel(String authorLevel) {
    this.authorLevel = authorLevel;
  }

  /**
   * 评论人性别 0保密 1男 2女
   **/
  @ApiModelProperty(value = "评论人性别 0保密 1男 2女")
  public String getAuthorSex() {
    return authorSex;
  }
  public void setAuthorSex(String authorSex) {
    this.authorSex = authorSex;
  }

  /**
   * 评论时间
   **/
  @ApiModelProperty(value = "评论时间")
  public String getPostdate() {
    return postdate;
  }
  public void setPostdate(String postdate) {
    this.postdate = postdate;
  }

  /**
   * 点赞数
   **/
  @ApiModelProperty(value = "点赞数")
  public String getPraiseCount() {
    return praiseCount;
  }
  public void setPraiseCount(String praiseCount) {
    this.praiseCount = praiseCount;
  }

  /**
   * 是否点赞 - 0：否 1：是
   **/
  @ApiModelProperty(value = "是否点赞 - 0：否 1：是")
  public String getIsPraised() {
    return isPraised;
  }
  public void setIsPraised(String isPraised) {
    this.isPraised = isPraised;
  }

  /**
   * 是否是子评论
   **/
  @ApiModelProperty(value = "是否是子评论")
  public String getIsSubReply() {
    return isSubReply;
  }
  public void setIsSubReply(String isSubReply) {
    this.isSubReply = isSubReply;
  }

  /**
   * 被评论的用户
   **/
  @ApiModelProperty(value = "被评论的用户")
  public String getReplyUsername() {
    return replyUsername;
  }
  public void setReplyUsername(String replyUsername) {
    this.replyUsername = replyUsername;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommentReplyModel commentReplyModel = (CommentReplyModel) o;
    return (commentId == null ? commentReplyModel.commentId == null : commentId.equals(commentReplyModel.commentId)) &&
        (author == null ? commentReplyModel.author == null : author.equals(commentReplyModel.author)) &&
        (authorid == null ? commentReplyModel.authorid == null : authorid.equals(commentReplyModel.authorid)) &&
        (source == null ? commentReplyModel.source == null : source.equals(commentReplyModel.source)) &&
        (comment == null ? commentReplyModel.comment == null : comment.equals(commentReplyModel.comment)) &&
        (avatar == null ? commentReplyModel.avatar == null : avatar.equals(commentReplyModel.avatar)) &&
        (authorGroupname == null ? commentReplyModel.authorGroupname == null : authorGroupname.equals(commentReplyModel.authorGroupname)) &&
        (authorLevel == null ? commentReplyModel.authorLevel == null : authorLevel.equals(commentReplyModel.authorLevel)) &&
        (authorSex == null ? commentReplyModel.authorSex == null : authorSex.equals(commentReplyModel.authorSex)) &&
        (postdate == null ? commentReplyModel.postdate == null : postdate.equals(commentReplyModel.postdate)) &&
        (praiseCount == null ? commentReplyModel.praiseCount == null : praiseCount.equals(commentReplyModel.praiseCount)) &&
        (isPraised == null ? commentReplyModel.isPraised == null : isPraised.equals(commentReplyModel.isPraised)) &&
        (isSubReply == null ? commentReplyModel.isSubReply == null : isSubReply.equals(commentReplyModel.isSubReply)) &&
        (replyUsername == null ? commentReplyModel.replyUsername == null : replyUsername.equals(commentReplyModel.replyUsername));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (commentId == null ? 0: commentId.hashCode());
    result = 31 * result + (author == null ? 0: author.hashCode());
    result = 31 * result + (authorid == null ? 0: authorid.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    result = 31 * result + (comment == null ? 0: comment.hashCode());
    result = 31 * result + (avatar == null ? 0: avatar.hashCode());
    result = 31 * result + (authorGroupname == null ? 0: authorGroupname.hashCode());
    result = 31 * result + (authorLevel == null ? 0: authorLevel.hashCode());
    result = 31 * result + (authorSex == null ? 0: authorSex.hashCode());
    result = 31 * result + (postdate == null ? 0: postdate.hashCode());
    result = 31 * result + (praiseCount == null ? 0: praiseCount.hashCode());
    result = 31 * result + (isPraised == null ? 0: isPraised.hashCode());
    result = 31 * result + (isSubReply == null ? 0: isSubReply.hashCode());
    result = 31 * result + (replyUsername == null ? 0: replyUsername.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommentReplyModel {\n");
    
    sb.append("  commentId: ").append(commentId).append("\n");
    sb.append("  author: ").append(author).append("\n");
    sb.append("  authorid: ").append(authorid).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  comment: ").append(comment).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  authorGroupname: ").append(authorGroupname).append("\n");
    sb.append("  authorLevel: ").append(authorLevel).append("\n");
    sb.append("  authorSex: ").append(authorSex).append("\n");
    sb.append("  postdate: ").append(postdate).append("\n");
    sb.append("  praiseCount: ").append(praiseCount).append("\n");
    sb.append("  isPraised: ").append(isPraised).append("\n");
    sb.append("  isSubReply: ").append(isSubReply).append("\n");
    sb.append("  replyUsername: ").append(replyUsername).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
