/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CompletingWordsIfModelData  {
  
  @SerializedName("keywords")
  private String keywords = null;
  @SerializedName("rebate_view")
  private String rebateView = null;

  /**
   * 关键词
   **/
  @ApiModelProperty(value = "关键词")
  public String getKeywords() {
    return keywords;
  }
  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  /**
   * 返利额度（文字说明）
   **/
  @ApiModelProperty(value = "返利额度（文字说明）")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompletingWordsIfModelData completingWordsIfModelData = (CompletingWordsIfModelData) o;
    return (keywords == null ? completingWordsIfModelData.keywords == null : keywords.equals(completingWordsIfModelData.keywords)) &&
        (rebateView == null ? completingWordsIfModelData.rebateView == null : rebateView.equals(completingWordsIfModelData.rebateView));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (keywords == null ? 0: keywords.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompletingWordsIfModelData {\n");
    
    sb.append("  keywords: ").append(keywords).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
