/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class CurrenciesIfModelData  {
  
  @SerializedName("country_flag")
  private String countryFlag = null;
  @SerializedName("currency_abbr")
  private String currencyAbbr = null;
  @SerializedName("currency_view")
  private String currencyView = null;
  @SerializedName("currency_name")
  private String currencyName = null;

  /**
   * 国旗图标
   **/
  @ApiModelProperty(value = "国旗图标")
  public String getCountryFlag() {
    return countryFlag;
  }
  public void setCountryFlag(String countryFlag) {
    this.countryFlag = countryFlag;
  }

  /**
   * 货币缩写
   **/
  @ApiModelProperty(value = "货币缩写")
  public String getCurrencyAbbr() {
    return currencyAbbr;
  }
  public void setCurrencyAbbr(String currencyAbbr) {
    this.currencyAbbr = currencyAbbr;
  }

  /**
   * 货币文字描述
   **/
  @ApiModelProperty(value = "货币文字描述")
  public String getCurrencyView() {
    return currencyView;
  }
  public void setCurrencyView(String currencyView) {
    this.currencyView = currencyView;
  }

  /**
   * 货币名称
   **/
  @ApiModelProperty(value = "货币名称")
  public String getCurrencyName() {
    return currencyName;
  }
  public void setCurrencyName(String currencyName) {
    this.currencyName = currencyName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrenciesIfModelData currenciesIfModelData = (CurrenciesIfModelData) o;
    return (countryFlag == null ? currenciesIfModelData.countryFlag == null : countryFlag.equals(currenciesIfModelData.countryFlag)) &&
        (currencyAbbr == null ? currenciesIfModelData.currencyAbbr == null : currencyAbbr.equals(currenciesIfModelData.currencyAbbr)) &&
        (currencyView == null ? currenciesIfModelData.currencyView == null : currencyView.equals(currenciesIfModelData.currencyView)) &&
        (currencyName == null ? currenciesIfModelData.currencyName == null : currencyName.equals(currenciesIfModelData.currencyName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (countryFlag == null ? 0: countryFlag.hashCode());
    result = 31 * result + (currencyAbbr == null ? 0: currencyAbbr.hashCode());
    result = 31 * result + (currencyView == null ? 0: currencyView.hashCode());
    result = 31 * result + (currencyName == null ? 0: currencyName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrenciesIfModelData {\n");
    
    sb.append("  countryFlag: ").append(countryFlag).append("\n");
    sb.append("  currencyAbbr: ").append(currencyAbbr).append("\n");
    sb.append("  currencyView: ").append(currencyView).append("\n");
    sb.append("  currencyName: ").append(currencyName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
