/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class DealDetailModelDataStoreInfo  {
  
  @SerializedName("store_logo")
  private String storeLogo = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_category_id")
  private String storeCategoryId = null;
  @SerializedName("store_category_name")
  private String storeCategoryName = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("country_flag_pic")
  private String countryFlagPic = null;
  @SerializedName("orders_count")
  private String ordersCount = null;
  @SerializedName("collections_count")
  private String collectionsCount = null;

  /**
   * 商家LOGO
   **/
  @ApiModelProperty(value = "商家LOGO")
  public String getStoreLogo() {
    return storeLogo;
  }
  public void setStoreLogo(String storeLogo) {
    this.storeLogo = storeLogo;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 商家类别ID
   **/
  @ApiModelProperty(value = "商家类别ID")
  public String getStoreCategoryId() {
    return storeCategoryId;
  }
  public void setStoreCategoryId(String storeCategoryId) {
    this.storeCategoryId = storeCategoryId;
  }

  /**
   * 商家类别名称
   **/
  @ApiModelProperty(value = "商家类别名称")
  public String getStoreCategoryName() {
    return storeCategoryName;
  }
  public void setStoreCategoryName(String storeCategoryName) {
    this.storeCategoryName = storeCategoryName;
  }

  /**
   * 返利信息（文字说明）
   **/
  @ApiModelProperty(value = "返利信息（文字说明）")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * 国旗图片
   **/
  @ApiModelProperty(value = "国旗图片")
  public String getCountryFlagPic() {
    return countryFlagPic;
  }
  public void setCountryFlagPic(String countryFlagPic) {
    this.countryFlagPic = countryFlagPic;
  }

  /**
   * 下单数量
   **/
  @ApiModelProperty(value = "下单数量")
  public String getOrdersCount() {
    return ordersCount;
  }
  public void setOrdersCount(String ordersCount) {
    this.ordersCount = ordersCount;
  }

  /**
   * 被收藏数
   **/
  @ApiModelProperty(value = "被收藏数")
  public String getCollectionsCount() {
    return collectionsCount;
  }
  public void setCollectionsCount(String collectionsCount) {
    this.collectionsCount = collectionsCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealDetailModelDataStoreInfo dealDetailModelDataStoreInfo = (DealDetailModelDataStoreInfo) o;
    return (storeLogo == null ? dealDetailModelDataStoreInfo.storeLogo == null : storeLogo.equals(dealDetailModelDataStoreInfo.storeLogo)) &&
        (storeName == null ? dealDetailModelDataStoreInfo.storeName == null : storeName.equals(dealDetailModelDataStoreInfo.storeName)) &&
        (storeCategoryId == null ? dealDetailModelDataStoreInfo.storeCategoryId == null : storeCategoryId.equals(dealDetailModelDataStoreInfo.storeCategoryId)) &&
        (storeCategoryName == null ? dealDetailModelDataStoreInfo.storeCategoryName == null : storeCategoryName.equals(dealDetailModelDataStoreInfo.storeCategoryName)) &&
        (rebateView == null ? dealDetailModelDataStoreInfo.rebateView == null : rebateView.equals(dealDetailModelDataStoreInfo.rebateView)) &&
        (countryFlagPic == null ? dealDetailModelDataStoreInfo.countryFlagPic == null : countryFlagPic.equals(dealDetailModelDataStoreInfo.countryFlagPic)) &&
        (ordersCount == null ? dealDetailModelDataStoreInfo.ordersCount == null : ordersCount.equals(dealDetailModelDataStoreInfo.ordersCount)) &&
        (collectionsCount == null ? dealDetailModelDataStoreInfo.collectionsCount == null : collectionsCount.equals(dealDetailModelDataStoreInfo.collectionsCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeLogo == null ? 0: storeLogo.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeCategoryId == null ? 0: storeCategoryId.hashCode());
    result = 31 * result + (storeCategoryName == null ? 0: storeCategoryName.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (countryFlagPic == null ? 0: countryFlagPic.hashCode());
    result = 31 * result + (ordersCount == null ? 0: ordersCount.hashCode());
    result = 31 * result + (collectionsCount == null ? 0: collectionsCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealDetailModelDataStoreInfo {\n");
    
    sb.append("  storeLogo: ").append(storeLogo).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeCategoryId: ").append(storeCategoryId).append("\n");
    sb.append("  storeCategoryName: ").append(storeCategoryName).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  countryFlagPic: ").append(countryFlagPic).append("\n");
    sb.append("  ordersCount: ").append(ordersCount).append("\n");
    sb.append("  collectionsCount: ").append(collectionsCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
