/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class DealDetailModelDataRecommendedTopics  {
  
  @SerializedName("pic")
  private String pic = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("author_name")
  private String authorName = null;
  @SerializedName("praise_count")
  private String praiseCount = null;
  @SerializedName("replies_count")
  private String repliesCount = null;
  @SerializedName("post_time")
  private String postTime = null;

  /**
   * 帖子图片
   **/
  @ApiModelProperty(value = "帖子图片")
  public String getPic() {
    return pic;
  }
  public void setPic(String pic) {
    this.pic = pic;
  }

  /**
   * 帖子标题
   **/
  @ApiModelProperty(value = "帖子标题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 作者名字
   **/
  @ApiModelProperty(value = "作者名字")
  public String getAuthorName() {
    return authorName;
  }
  public void setAuthorName(String authorName) {
    this.authorName = authorName;
  }

  /**
   * 点赞数
   **/
  @ApiModelProperty(value = "点赞数")
  public String getPraiseCount() {
    return praiseCount;
  }
  public void setPraiseCount(String praiseCount) {
    this.praiseCount = praiseCount;
  }

  /**
   * 回复数
   **/
  @ApiModelProperty(value = "回复数")
  public String getRepliesCount() {
    return repliesCount;
  }
  public void setRepliesCount(String repliesCount) {
    this.repliesCount = repliesCount;
  }

  /**
   * 发布时间
   **/
  @ApiModelProperty(value = "发布时间")
  public String getPostTime() {
    return postTime;
  }
  public void setPostTime(String postTime) {
    this.postTime = postTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealDetailModelDataRecommendedTopics dealDetailModelDataRecommendedTopics = (DealDetailModelDataRecommendedTopics) o;
    return (pic == null ? dealDetailModelDataRecommendedTopics.pic == null : pic.equals(dealDetailModelDataRecommendedTopics.pic)) &&
        (title == null ? dealDetailModelDataRecommendedTopics.title == null : title.equals(dealDetailModelDataRecommendedTopics.title)) &&
        (authorName == null ? dealDetailModelDataRecommendedTopics.authorName == null : authorName.equals(dealDetailModelDataRecommendedTopics.authorName)) &&
        (praiseCount == null ? dealDetailModelDataRecommendedTopics.praiseCount == null : praiseCount.equals(dealDetailModelDataRecommendedTopics.praiseCount)) &&
        (repliesCount == null ? dealDetailModelDataRecommendedTopics.repliesCount == null : repliesCount.equals(dealDetailModelDataRecommendedTopics.repliesCount)) &&
        (postTime == null ? dealDetailModelDataRecommendedTopics.postTime == null : postTime.equals(dealDetailModelDataRecommendedTopics.postTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (pic == null ? 0: pic.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (authorName == null ? 0: authorName.hashCode());
    result = 31 * result + (praiseCount == null ? 0: praiseCount.hashCode());
    result = 31 * result + (repliesCount == null ? 0: repliesCount.hashCode());
    result = 31 * result + (postTime == null ? 0: postTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealDetailModelDataRecommendedTopics {\n");
    
    sb.append("  pic: ").append(pic).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  authorName: ").append(authorName).append("\n");
    sb.append("  praiseCount: ").append(praiseCount).append("\n");
    sb.append("  repliesCount: ").append(repliesCount).append("\n");
    sb.append("  postTime: ").append(postTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
