/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class DealIndexModelDataTodayTalkTopic  {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("tid")
  private String tid = null;

  /**
   * 今日话题
   **/
  @ApiModelProperty(value = "今日话题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 话题帖ID
   **/
  @ApiModelProperty(value = "话题帖ID")
  public String getTid() {
    return tid;
  }
  public void setTid(String tid) {
    this.tid = tid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealIndexModelDataTodayTalkTopic dealIndexModelDataTodayTalkTopic = (DealIndexModelDataTodayTalkTopic) o;
    return (title == null ? dealIndexModelDataTodayTalkTopic.title == null : title.equals(dealIndexModelDataTodayTalkTopic.title)) &&
        (tid == null ? dealIndexModelDataTodayTalkTopic.tid == null : tid.equals(dealIndexModelDataTodayTalkTopic.tid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (tid == null ? 0: tid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealIndexModelDataTodayTalkTopic {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  tid: ").append(tid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
