/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.DealModel;
import io.swagger.client.model.SlidePicModel;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class DealsWithAdsModel  {
  
  @SerializedName("cross_bar_pics")
  private List<SlidePicModel> crossBarPics = null;
  @SerializedName("rows")
  private List<DealModel> rows = null;

  /**
   * 首页横幅
   **/
  @ApiModelProperty(value = "首页横幅")
  public List<SlidePicModel> getCrossBarPics() {
    return crossBarPics;
  }
  public void setCrossBarPics(List<SlidePicModel> crossBarPics) {
    this.crossBarPics = crossBarPics;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<DealModel> getRows() {
    return rows;
  }
  public void setRows(List<DealModel> rows) {
    this.rows = rows;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DealsWithAdsModel dealsWithAdsModel = (DealsWithAdsModel) o;
    return (crossBarPics == null ? dealsWithAdsModel.crossBarPics == null : crossBarPics.equals(dealsWithAdsModel.crossBarPics)) &&
        (rows == null ? dealsWithAdsModel.rows == null : rows.equals(dealsWithAdsModel.rows));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (crossBarPics == null ? 0: crossBarPics.hashCode());
    result = 31 * result + (rows == null ? 0: rows.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DealsWithAdsModel {\n");
    
    sb.append("  crossBarPics: ").append(crossBarPics).append("\n");
    sb.append("  rows: ").append(rows).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
