/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.5接口 
 *
 * OpenAPI spec version: 1.4 build20170919-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.AppMenuWidgetModel;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class EntryModel  {
  
  @SerializedName("key")
  private String key = null;
  @SerializedName("widget")
  private AppMenuWidgetModel widget = null;

  /**
   * 快捷入口唯一标识符
   **/
  @ApiModelProperty(value = "快捷入口唯一标识符")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AppMenuWidgetModel getWidget() {
    return widget;
  }
  public void setWidget(AppMenuWidgetModel widget) {
    this.widget = widget;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntryModel entryModel = (EntryModel) o;
    return (key == null ? entryModel.key == null : key.equals(entryModel.key)) &&
        (widget == null ? entryModel.widget == null : widget.equals(entryModel.widget));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (key == null ? 0: key.hashCode());
    result = 31 * result + (widget == null ? 0: widget.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntryModel {\n");
    
    sb.append("  key: ").append(key).append("\n");
    sb.append("  widget: ").append(widget).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
