/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ExchangeRateModel  {
  
  @SerializedName("from")
  private String from = null;
  @SerializedName("to")
  private String to = null;
  @SerializedName("from_view")
  private String fromView = null;
  @SerializedName("to_view")
  private String toView = null;
  @SerializedName("from_country_flag")
  private String fromCountryFlag = null;
  @SerializedName("to_country_flag")
  private String toCountryFlag = null;
  @SerializedName("rate")
  private String rate = null;
  @SerializedName("last_update_time")
  private String lastUpdateTime = null;

  /**
   * 原始货币缩写
   **/
  @ApiModelProperty(value = "原始货币缩写")
  public String getFrom() {
    return from;
  }
  public void setFrom(String from) {
    this.from = from;
  }

  /**
   * 兑换货币缩写
   **/
  @ApiModelProperty(value = "兑换货币缩写")
  public String getTo() {
    return to;
  }
  public void setTo(String to) {
    this.to = to;
  }

  /**
   * 原始货币文字描述
   **/
  @ApiModelProperty(value = "原始货币文字描述")
  public String getFromView() {
    return fromView;
  }
  public void setFromView(String fromView) {
    this.fromView = fromView;
  }

  /**
   * 兑换货币文字描述
   **/
  @ApiModelProperty(value = "兑换货币文字描述")
  public String getToView() {
    return toView;
  }
  public void setToView(String toView) {
    this.toView = toView;
  }

  /**
   * 原始货币所属国家的国旗
   **/
  @ApiModelProperty(value = "原始货币所属国家的国旗")
  public String getFromCountryFlag() {
    return fromCountryFlag;
  }
  public void setFromCountryFlag(String fromCountryFlag) {
    this.fromCountryFlag = fromCountryFlag;
  }

  /**
   * 兑换货币所属国家的国旗
   **/
  @ApiModelProperty(value = "兑换货币所属国家的国旗")
  public String getToCountryFlag() {
    return toCountryFlag;
  }
  public void setToCountryFlag(String toCountryFlag) {
    this.toCountryFlag = toCountryFlag;
  }

  /**
   * 兑换比率
   **/
  @ApiModelProperty(value = "兑换比率")
  public String getRate() {
    return rate;
  }
  public void setRate(String rate) {
    this.rate = rate;
  }

  /**
   * 最后更新时间
   **/
  @ApiModelProperty(value = "最后更新时间")
  public String getLastUpdateTime() {
    return lastUpdateTime;
  }
  public void setLastUpdateTime(String lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeRateModel exchangeRateModel = (ExchangeRateModel) o;
    return (from == null ? exchangeRateModel.from == null : from.equals(exchangeRateModel.from)) &&
        (to == null ? exchangeRateModel.to == null : to.equals(exchangeRateModel.to)) &&
        (fromView == null ? exchangeRateModel.fromView == null : fromView.equals(exchangeRateModel.fromView)) &&
        (toView == null ? exchangeRateModel.toView == null : toView.equals(exchangeRateModel.toView)) &&
        (fromCountryFlag == null ? exchangeRateModel.fromCountryFlag == null : fromCountryFlag.equals(exchangeRateModel.fromCountryFlag)) &&
        (toCountryFlag == null ? exchangeRateModel.toCountryFlag == null : toCountryFlag.equals(exchangeRateModel.toCountryFlag)) &&
        (rate == null ? exchangeRateModel.rate == null : rate.equals(exchangeRateModel.rate)) &&
        (lastUpdateTime == null ? exchangeRateModel.lastUpdateTime == null : lastUpdateTime.equals(exchangeRateModel.lastUpdateTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (from == null ? 0: from.hashCode());
    result = 31 * result + (to == null ? 0: to.hashCode());
    result = 31 * result + (fromView == null ? 0: fromView.hashCode());
    result = 31 * result + (toView == null ? 0: toView.hashCode());
    result = 31 * result + (fromCountryFlag == null ? 0: fromCountryFlag.hashCode());
    result = 31 * result + (toCountryFlag == null ? 0: toCountryFlag.hashCode());
    result = 31 * result + (rate == null ? 0: rate.hashCode());
    result = 31 * result + (lastUpdateTime == null ? 0: lastUpdateTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeRateModel {\n");
    
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  fromView: ").append(fromView).append("\n");
    sb.append("  toView: ").append(toView).append("\n");
    sb.append("  fromCountryFlag: ").append(fromCountryFlag).append("\n");
    sb.append("  toCountryFlag: ").append(toCountryFlag).append("\n");
    sb.append("  rate: ").append(rate).append("\n");
    sb.append("  lastUpdateTime: ").append(lastUpdateTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
