/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class FollowingDealModel  {
  
  @SerializedName("task_id")
  private String taskId = null;
  @SerializedName("deal_id")
  private String dealId = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("price_view")
  private String priceView = null;
  @SerializedName("original_price")
  private String originalPrice = null;
  @SerializedName("now_price")
  private String nowPrice = null;
  @SerializedName("currency_symbol")
  private String currencySymbol = null;
  @SerializedName("currency_abbr")
  private String currencyAbbr = null;
  @SerializedName("deal_pic")
  private String dealPic = null;
  @SerializedName("deal_pic_origin")
  private String dealPicOrigin = null;
  @SerializedName("is_expired")
  private String isExpired = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("country_id")
  private String countryId = null;
  @SerializedName("country_name")
  private String countryName = null;
  @SerializedName("country_abbr")
  private String countryAbbr = null;
  @SerializedName("country_flag_pic")
  private String countryFlagPic = null;
  @SerializedName("deal_url")
  private String dealUrl = null;

  /**
   * 提醒项ID
   **/
  @ApiModelProperty(value = "提醒项ID")
  public String getTaskId() {
    return taskId;
  }
  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  /**
   * 优惠ID
   **/
  @ApiModelProperty(value = "优惠ID")
  public String getDealId() {
    return dealId;
  }
  public void setDealId(String dealId) {
    this.dealId = dealId;
  }

  /**
   * 优惠标题
   **/
  @ApiModelProperty(value = "优惠标题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 显示价格
   **/
  @ApiModelProperty(value = "显示价格")
  public String getPriceView() {
    return priceView;
  }
  public void setPriceView(String priceView) {
    this.priceView = priceView;
  }

  /**
   * 原价
   **/
  @ApiModelProperty(value = "原价")
  public String getOriginalPrice() {
    return originalPrice;
  }
  public void setOriginalPrice(String originalPrice) {
    this.originalPrice = originalPrice;
  }

  /**
   * 现价
   **/
  @ApiModelProperty(value = "现价")
  public String getNowPrice() {
    return nowPrice;
  }
  public void setNowPrice(String nowPrice) {
    this.nowPrice = nowPrice;
  }

  /**
   * 货币符号
   **/
  @ApiModelProperty(value = "货币符号")
  public String getCurrencySymbol() {
    return currencySymbol;
  }
  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  /**
   * 货币缩写
   **/
  @ApiModelProperty(value = "货币缩写")
  public String getCurrencyAbbr() {
    return currencyAbbr;
  }
  public void setCurrencyAbbr(String currencyAbbr) {
    this.currencyAbbr = currencyAbbr;
  }

  /**
   * 优惠图片
   **/
  @ApiModelProperty(value = "优惠图片")
  public String getDealPic() {
    return dealPic;
  }
  public void setDealPic(String dealPic) {
    this.dealPic = dealPic;
  }

  /**
   * 优惠图片原始地址
   **/
  @ApiModelProperty(value = "优惠图片原始地址")
  public String getDealPicOrigin() {
    return dealPicOrigin;
  }
  public void setDealPicOrigin(String dealPicOrigin) {
    this.dealPicOrigin = dealPicOrigin;
  }

  /**
   * 是否已过期
   **/
  @ApiModelProperty(value = "是否已过期")
  public String getIsExpired() {
    return isExpired;
  }
  public void setIsExpired(String isExpired) {
    this.isExpired = isExpired;
  }

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 国家ID
   **/
  @ApiModelProperty(value = "国家ID")
  public String getCountryId() {
    return countryId;
  }
  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  /**
   * 国家名称
   **/
  @ApiModelProperty(value = "国家名称")
  public String getCountryName() {
    return countryName;
  }
  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  /**
   * 国家缩写
   **/
  @ApiModelProperty(value = "国家缩写")
  public String getCountryAbbr() {
    return countryAbbr;
  }
  public void setCountryAbbr(String countryAbbr) {
    this.countryAbbr = countryAbbr;
  }

  /**
   * 国旗图片
   **/
  @ApiModelProperty(value = "国旗图片")
  public String getCountryFlagPic() {
    return countryFlagPic;
  }
  public void setCountryFlagPic(String countryFlagPic) {
    this.countryFlagPic = countryFlagPic;
  }

  /**
   * 优惠去购买链接
   **/
  @ApiModelProperty(value = "优惠去购买链接")
  public String getDealUrl() {
    return dealUrl;
  }
  public void setDealUrl(String dealUrl) {
    this.dealUrl = dealUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FollowingDealModel followingDealModel = (FollowingDealModel) o;
    return (taskId == null ? followingDealModel.taskId == null : taskId.equals(followingDealModel.taskId)) &&
        (dealId == null ? followingDealModel.dealId == null : dealId.equals(followingDealModel.dealId)) &&
        (title == null ? followingDealModel.title == null : title.equals(followingDealModel.title)) &&
        (priceView == null ? followingDealModel.priceView == null : priceView.equals(followingDealModel.priceView)) &&
        (originalPrice == null ? followingDealModel.originalPrice == null : originalPrice.equals(followingDealModel.originalPrice)) &&
        (nowPrice == null ? followingDealModel.nowPrice == null : nowPrice.equals(followingDealModel.nowPrice)) &&
        (currencySymbol == null ? followingDealModel.currencySymbol == null : currencySymbol.equals(followingDealModel.currencySymbol)) &&
        (currencyAbbr == null ? followingDealModel.currencyAbbr == null : currencyAbbr.equals(followingDealModel.currencyAbbr)) &&
        (dealPic == null ? followingDealModel.dealPic == null : dealPic.equals(followingDealModel.dealPic)) &&
        (dealPicOrigin == null ? followingDealModel.dealPicOrigin == null : dealPicOrigin.equals(followingDealModel.dealPicOrigin)) &&
        (isExpired == null ? followingDealModel.isExpired == null : isExpired.equals(followingDealModel.isExpired)) &&
        (storeId == null ? followingDealModel.storeId == null : storeId.equals(followingDealModel.storeId)) &&
        (storeName == null ? followingDealModel.storeName == null : storeName.equals(followingDealModel.storeName)) &&
        (countryId == null ? followingDealModel.countryId == null : countryId.equals(followingDealModel.countryId)) &&
        (countryName == null ? followingDealModel.countryName == null : countryName.equals(followingDealModel.countryName)) &&
        (countryAbbr == null ? followingDealModel.countryAbbr == null : countryAbbr.equals(followingDealModel.countryAbbr)) &&
        (countryFlagPic == null ? followingDealModel.countryFlagPic == null : countryFlagPic.equals(followingDealModel.countryFlagPic)) &&
        (dealUrl == null ? followingDealModel.dealUrl == null : dealUrl.equals(followingDealModel.dealUrl));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (taskId == null ? 0: taskId.hashCode());
    result = 31 * result + (dealId == null ? 0: dealId.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (priceView == null ? 0: priceView.hashCode());
    result = 31 * result + (originalPrice == null ? 0: originalPrice.hashCode());
    result = 31 * result + (nowPrice == null ? 0: nowPrice.hashCode());
    result = 31 * result + (currencySymbol == null ? 0: currencySymbol.hashCode());
    result = 31 * result + (currencyAbbr == null ? 0: currencyAbbr.hashCode());
    result = 31 * result + (dealPic == null ? 0: dealPic.hashCode());
    result = 31 * result + (dealPicOrigin == null ? 0: dealPicOrigin.hashCode());
    result = 31 * result + (isExpired == null ? 0: isExpired.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (countryId == null ? 0: countryId.hashCode());
    result = 31 * result + (countryName == null ? 0: countryName.hashCode());
    result = 31 * result + (countryAbbr == null ? 0: countryAbbr.hashCode());
    result = 31 * result + (countryFlagPic == null ? 0: countryFlagPic.hashCode());
    result = 31 * result + (dealUrl == null ? 0: dealUrl.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FollowingDealModel {\n");
    
    sb.append("  taskId: ").append(taskId).append("\n");
    sb.append("  dealId: ").append(dealId).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  priceView: ").append(priceView).append("\n");
    sb.append("  originalPrice: ").append(originalPrice).append("\n");
    sb.append("  nowPrice: ").append(nowPrice).append("\n");
    sb.append("  currencySymbol: ").append(currencySymbol).append("\n");
    sb.append("  currencyAbbr: ").append(currencyAbbr).append("\n");
    sb.append("  dealPic: ").append(dealPic).append("\n");
    sb.append("  dealPicOrigin: ").append(dealPicOrigin).append("\n");
    sb.append("  isExpired: ").append(isExpired).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  countryId: ").append(countryId).append("\n");
    sb.append("  countryName: ").append(countryName).append("\n");
    sb.append("  countryAbbr: ").append(countryAbbr).append("\n");
    sb.append("  countryFlagPic: ").append(countryFlagPic).append("\n");
    sb.append("  dealUrl: ").append(dealUrl).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
