/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ForumUserInfoModel  {
  
  @SerializedName("uid")
  private String uid = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("group_name")
  private String groupName = null;
  @SerializedName("topics_count")
  private String topicsCount = null;
  @SerializedName("posts_count")
  private String postsCount = null;
  @SerializedName("digest_topics_count")
  private String digestTopicsCount = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("is_friend")
  private String isFriend = null;

  /**
   * 用户ID
   **/
  @ApiModelProperty(value = "用户ID")
  public String getUid() {
    return uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   * 用户名
   **/
  @ApiModelProperty(value = "用户名")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * 用户组名
   **/
  @ApiModelProperty(value = "用户组名")
  public String getGroupName() {
    return groupName;
  }
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  /**
   * 主题数
   **/
  @ApiModelProperty(value = "主题数")
  public String getTopicsCount() {
    return topicsCount;
  }
  public void setTopicsCount(String topicsCount) {
    this.topicsCount = topicsCount;
  }

  /**
   * 回复数
   **/
  @ApiModelProperty(value = "回复数")
  public String getPostsCount() {
    return postsCount;
  }
  public void setPostsCount(String postsCount) {
    this.postsCount = postsCount;
  }

  /**
   * 精华帖数
   **/
  @ApiModelProperty(value = "精华帖数")
  public String getDigestTopicsCount() {
    return digestTopicsCount;
  }
  public void setDigestTopicsCount(String digestTopicsCount) {
    this.digestTopicsCount = digestTopicsCount;
  }

  /**
   * 用户头像
   **/
  @ApiModelProperty(value = "用户头像")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * 是否是好友 - 0：不是好友 1：已是好友 2：自己 3:已向对方发送过好友请求 4：对方请求添加我为好友
   **/
  @ApiModelProperty(value = "是否是好友 - 0：不是好友 1：已是好友 2：自己 3:已向对方发送过好友请求 4：对方请求添加我为好友")
  public String getIsFriend() {
    return isFriend;
  }
  public void setIsFriend(String isFriend) {
    this.isFriend = isFriend;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForumUserInfoModel forumUserInfoModel = (ForumUserInfoModel) o;
    return (uid == null ? forumUserInfoModel.uid == null : uid.equals(forumUserInfoModel.uid)) &&
        (username == null ? forumUserInfoModel.username == null : username.equals(forumUserInfoModel.username)) &&
        (groupName == null ? forumUserInfoModel.groupName == null : groupName.equals(forumUserInfoModel.groupName)) &&
        (topicsCount == null ? forumUserInfoModel.topicsCount == null : topicsCount.equals(forumUserInfoModel.topicsCount)) &&
        (postsCount == null ? forumUserInfoModel.postsCount == null : postsCount.equals(forumUserInfoModel.postsCount)) &&
        (digestTopicsCount == null ? forumUserInfoModel.digestTopicsCount == null : digestTopicsCount.equals(forumUserInfoModel.digestTopicsCount)) &&
        (avatar == null ? forumUserInfoModel.avatar == null : avatar.equals(forumUserInfoModel.avatar)) &&
        (isFriend == null ? forumUserInfoModel.isFriend == null : isFriend.equals(forumUserInfoModel.isFriend));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (uid == null ? 0: uid.hashCode());
    result = 31 * result + (username == null ? 0: username.hashCode());
    result = 31 * result + (groupName == null ? 0: groupName.hashCode());
    result = 31 * result + (topicsCount == null ? 0: topicsCount.hashCode());
    result = 31 * result + (postsCount == null ? 0: postsCount.hashCode());
    result = 31 * result + (digestTopicsCount == null ? 0: digestTopicsCount.hashCode());
    result = 31 * result + (avatar == null ? 0: avatar.hashCode());
    result = 31 * result + (isFriend == null ? 0: isFriend.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForumUserInfoModel {\n");
    
    sb.append("  uid: ").append(uid).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  groupName: ").append(groupName).append("\n");
    sb.append("  topicsCount: ").append(topicsCount).append("\n");
    sb.append("  postsCount: ").append(postsCount).append("\n");
    sb.append("  digestTopicsCount: ").append(digestTopicsCount).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  isFriend: ").append(isFriend).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
