/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.ForumBoardModel;
import io.swagger.client.model.ForumSectionModel;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ForumBoardsIndexModelData  {
  
  @SerializedName("sections")
  private List<ForumSectionModel> sections = null;
  @SerializedName("boards")
  private List<ForumBoardModel> boards = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ForumSectionModel> getSections() {
    return sections;
  }
  public void setSections(List<ForumSectionModel> sections) {
    this.sections = sections;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ForumBoardModel> getBoards() {
    return boards;
  }
  public void setBoards(List<ForumBoardModel> boards) {
    this.boards = boards;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForumBoardsIndexModelData forumBoardsIndexModelData = (ForumBoardsIndexModelData) o;
    return (sections == null ? forumBoardsIndexModelData.sections == null : sections.equals(forumBoardsIndexModelData.sections)) &&
        (boards == null ? forumBoardsIndexModelData.boards == null : boards.equals(forumBoardsIndexModelData.boards));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (sections == null ? 0: sections.hashCode());
    result = 31 * result + (boards == null ? 0: boards.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForumBoardsIndexModelData {\n");
    
    sb.append("  sections: ").append(sections).append("\n");
    sb.append("  boards: ").append(boards).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
