/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class LinkWidgetModel  {
  
  @SerializedName("style_id")
  private String styleId = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("widget_id")
  private String widgetId = null;
  @SerializedName("link_title")
  private String linkTitle = null;
  @SerializedName("link_type")
  private String linkType = null;
  @SerializedName("link_data")
  private String linkData = null;

  /**
   * 风格ID
   **/
  @ApiModelProperty(value = "风格ID")
  public String getStyleId() {
    return styleId;
  }
  public void setStyleId(String styleId) {
    this.styleId = styleId;
  }

  /**
   * 标题文字
   **/
  @ApiModelProperty(value = "标题文字")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 控件ID - deal_nav_{category_id}：优惠分类ID deal_nav_activity:优惠分类导航栏活动入口ID tab_deal:优惠TABID tab_discover:发现TABID tab_forum:论坛TABID tab_msgs:消息TABID tab_mine:我的TABID tab_activity:活动TABID deal_index_signing:每日签到入口ID deal_index_stores:返利商家入口ID deal_index_transshippers:转运物流入口ID deal_index_inviting:邀请好友入口ID
   **/
  @ApiModelProperty(value = "控件ID - deal_nav_{category_id}：优惠分类ID deal_nav_activity:优惠分类导航栏活动入口ID tab_deal:优惠TABID tab_discover:发现TABID tab_forum:论坛TABID tab_msgs:消息TABID tab_mine:我的TABID tab_activity:活动TABID deal_index_signing:每日签到入口ID deal_index_stores:返利商家入口ID deal_index_transshippers:转运物流入口ID deal_index_inviting:邀请好友入口ID")
  public String getWidgetId() {
    return widgetId;
  }
  public void setWidgetId(String widgetId) {
    this.widgetId = widgetId;
  }

  /**
   * 跳转标题
   **/
  @ApiModelProperty(value = "跳转标题")
  public String getLinkTitle() {
    return linkTitle;
  }
  public void setLinkTitle(String linkTitle) {
    this.linkTitle = linkTitle;
  }

  /**
   * d：优惠跳转, s：商家跳转, b：帖子详情, w：H5, sp：保留的老版本类型, l：邀请好友-未登录时跳转注册, trans：转运, section：版块, user：用户详情, tag：标签详情, exchange：兑换详情, trial：试用详情, invite：邀请好友, appstore：应用商店, outapp：外部浏览器打开，sign:每日签到, trial_list：试用列表， 兑换列表：exchange_list，store_list：返利商家列表，trans_list:转运商家列表，dealDaily_list：优惠日报列表, popular: 热销榜， promotion：降价榜， deal_subscrib：优惠订阅，offline_rebate：线下返利
   **/
  @ApiModelProperty(value = "d：优惠跳转, s：商家跳转, b：帖子详情, w：H5, sp：保留的老版本类型, l：邀请好友-未登录时跳转注册, trans：转运, section：版块, user：用户详情, tag：标签详情, exchange：兑换详情, trial：试用详情, invite：邀请好友, appstore：应用商店, outapp：外部浏览器打开，sign:每日签到, trial_list：试用列表， 兑换列表：exchange_list，store_list：返利商家列表，trans_list:转运商家列表，dealDaily_list：优惠日报列表, popular: 热销榜， promotion：降价榜， deal_subscrib：优惠订阅，offline_rebate：线下返利")
  public String getLinkType() {
    return linkType;
  }
  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }

  /**
   * 跳转目标内容
   **/
  @ApiModelProperty(value = "跳转目标内容")
  public String getLinkData() {
    return linkData;
  }
  public void setLinkData(String linkData) {
    this.linkData = linkData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkWidgetModel linkWidgetModel = (LinkWidgetModel) o;
    return (styleId == null ? linkWidgetModel.styleId == null : styleId.equals(linkWidgetModel.styleId)) &&
        (title == null ? linkWidgetModel.title == null : title.equals(linkWidgetModel.title)) &&
        (widgetId == null ? linkWidgetModel.widgetId == null : widgetId.equals(linkWidgetModel.widgetId)) &&
        (linkTitle == null ? linkWidgetModel.linkTitle == null : linkTitle.equals(linkWidgetModel.linkTitle)) &&
        (linkType == null ? linkWidgetModel.linkType == null : linkType.equals(linkWidgetModel.linkType)) &&
        (linkData == null ? linkWidgetModel.linkData == null : linkData.equals(linkWidgetModel.linkData));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (styleId == null ? 0: styleId.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (widgetId == null ? 0: widgetId.hashCode());
    result = 31 * result + (linkTitle == null ? 0: linkTitle.hashCode());
    result = 31 * result + (linkType == null ? 0: linkType.hashCode());
    result = 31 * result + (linkData == null ? 0: linkData.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkWidgetModel {\n");
    
    sb.append("  styleId: ").append(styleId).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  widgetId: ").append(widgetId).append("\n");
    sb.append("  linkTitle: ").append(linkTitle).append("\n");
    sb.append("  linkType: ").append(linkType).append("\n");
    sb.append("  linkData: ").append(linkData).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
