/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class LoginSuccessModelData  {
  
  @SerializedName("token")
  private String token = null;
  @SerializedName("refresh_token")
  private String refreshToken = null;
  @SerializedName("uid")
  private String uid = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("mobile")
  private String mobile = null;
  @SerializedName("mobile_unique")
  private String mobileUnique = null;

  /**
   * token
   **/
  @ApiModelProperty(value = "token")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   * refresh_token
   **/
  @ApiModelProperty(value = "refresh_token")
  public String getRefreshToken() {
    return refreshToken;
  }
  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }

  /**
   * 用户ID
   **/
  @ApiModelProperty(value = "用户ID")
  public String getUid() {
    return uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   * 用户名
   **/
  @ApiModelProperty(value = "用户名")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * 手机号
   **/
  @ApiModelProperty(value = "手机号")
  public String getMobile() {
    return mobile;
  }
  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  /**
   * 手机号是否被重复绑定 - 1：是 0：否
   **/
  @ApiModelProperty(value = "手机号是否被重复绑定 - 1：是 0：否")
  public String getMobileUnique() {
    return mobileUnique;
  }
  public void setMobileUnique(String mobileUnique) {
    this.mobileUnique = mobileUnique;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginSuccessModelData loginSuccessModelData = (LoginSuccessModelData) o;
    return (token == null ? loginSuccessModelData.token == null : token.equals(loginSuccessModelData.token)) &&
        (refreshToken == null ? loginSuccessModelData.refreshToken == null : refreshToken.equals(loginSuccessModelData.refreshToken)) &&
        (uid == null ? loginSuccessModelData.uid == null : uid.equals(loginSuccessModelData.uid)) &&
        (username == null ? loginSuccessModelData.username == null : username.equals(loginSuccessModelData.username)) &&
        (mobile == null ? loginSuccessModelData.mobile == null : mobile.equals(loginSuccessModelData.mobile)) &&
        (mobileUnique == null ? loginSuccessModelData.mobileUnique == null : mobileUnique.equals(loginSuccessModelData.mobileUnique));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (token == null ? 0: token.hashCode());
    result = 31 * result + (refreshToken == null ? 0: refreshToken.hashCode());
    result = 31 * result + (uid == null ? 0: uid.hashCode());
    result = 31 * result + (username == null ? 0: username.hashCode());
    result = 31 * result + (mobile == null ? 0: mobile.hashCode());
    result = 31 * result + (mobileUnique == null ? 0: mobileUnique.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginSuccessModelData {\n");
    
    sb.append("  token: ").append(token).append("\n");
    sb.append("  refreshToken: ").append(refreshToken).append("\n");
    sb.append("  uid: ").append(uid).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  mobile: ").append(mobile).append("\n");
    sb.append("  mobileUnique: ").append(mobileUnique).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
