/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.MyReplyModelSource;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class MyReplyModel  {
  
  @SerializedName("tid")
  private String tid = null;
  @SerializedName("pid")
  private String pid = null;
  @SerializedName("floor_num")
  private String floorNum = null;
  @SerializedName("content")
  private String content = null;
  @SerializedName("pics")
  private List<String> pics = null;
  @SerializedName("source")
  private MyReplyModelSource source = null;
  @SerializedName("reply_time")
  private String replyTime = null;

  /**
   * 主题ID
   **/
  @ApiModelProperty(value = "主题ID")
  public String getTid() {
    return tid;
  }
  public void setTid(String tid) {
    this.tid = tid;
  }

  /**
   * 回复ID
   **/
  @ApiModelProperty(value = "回复ID")
  public String getPid() {
    return pid;
  }
  public void setPid(String pid) {
    this.pid = pid;
  }

  /**
   * 回复楼层编号
   **/
  @ApiModelProperty(value = "回复楼层编号")
  public String getFloorNum() {
    return floorNum;
  }
  public void setFloorNum(String floorNum) {
    this.floorNum = floorNum;
  }

  /**
   * 回复内容
   **/
  @ApiModelProperty(value = "回复内容")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * 回复内容中的图片
   **/
  @ApiModelProperty(value = "回复内容中的图片")
  public List<String> getPics() {
    return pics;
  }
  public void setPics(List<String> pics) {
    this.pics = pics;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MyReplyModelSource getSource() {
    return source;
  }
  public void setSource(MyReplyModelSource source) {
    this.source = source;
  }

  /**
   * 回复时间
   **/
  @ApiModelProperty(value = "回复时间")
  public String getReplyTime() {
    return replyTime;
  }
  public void setReplyTime(String replyTime) {
    this.replyTime = replyTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyReplyModel myReplyModel = (MyReplyModel) o;
    return (tid == null ? myReplyModel.tid == null : tid.equals(myReplyModel.tid)) &&
        (pid == null ? myReplyModel.pid == null : pid.equals(myReplyModel.pid)) &&
        (floorNum == null ? myReplyModel.floorNum == null : floorNum.equals(myReplyModel.floorNum)) &&
        (content == null ? myReplyModel.content == null : content.equals(myReplyModel.content)) &&
        (pics == null ? myReplyModel.pics == null : pics.equals(myReplyModel.pics)) &&
        (source == null ? myReplyModel.source == null : source.equals(myReplyModel.source)) &&
        (replyTime == null ? myReplyModel.replyTime == null : replyTime.equals(myReplyModel.replyTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (tid == null ? 0: tid.hashCode());
    result = 31 * result + (pid == null ? 0: pid.hashCode());
    result = 31 * result + (floorNum == null ? 0: floorNum.hashCode());
    result = 31 * result + (content == null ? 0: content.hashCode());
    result = 31 * result + (pics == null ? 0: pics.hashCode());
    result = 31 * result + (source == null ? 0: source.hashCode());
    result = 31 * result + (replyTime == null ? 0: replyTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyReplyModel {\n");
    
    sb.append("  tid: ").append(tid).append("\n");
    sb.append("  pid: ").append(pid).append("\n");
    sb.append("  floorNum: ").append(floorNum).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  pics: ").append(pics).append("\n");
    sb.append("  source: ").append(source).append("\n");
    sb.append("  replyTime: ").append(replyTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
