/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.OfflineStoreAddressListModelLists;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class OfflineStoreAddressListModelLists1  {
  
  @SerializedName("city_id")
  private String cityId = null;
  @SerializedName("city_name")
  private String cityName = null;
  @SerializedName("lists")
  private List<OfflineStoreAddressListModelLists> lists = null;

  /**
   * 城市ID
   **/
  @ApiModelProperty(value = "城市ID")
  public String getCityId() {
    return cityId;
  }
  public void setCityId(String cityId) {
    this.cityId = cityId;
  }

  /**
   * 城市名称
   **/
  @ApiModelProperty(value = "城市名称")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   * 详细地址列表
   **/
  @ApiModelProperty(value = "详细地址列表")
  public List<OfflineStoreAddressListModelLists> getLists() {
    return lists;
  }
  public void setLists(List<OfflineStoreAddressListModelLists> lists) {
    this.lists = lists;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfflineStoreAddressListModelLists1 offlineStoreAddressListModelLists1 = (OfflineStoreAddressListModelLists1) o;
    return (cityId == null ? offlineStoreAddressListModelLists1.cityId == null : cityId.equals(offlineStoreAddressListModelLists1.cityId)) &&
        (cityName == null ? offlineStoreAddressListModelLists1.cityName == null : cityName.equals(offlineStoreAddressListModelLists1.cityName)) &&
        (lists == null ? offlineStoreAddressListModelLists1.lists == null : lists.equals(offlineStoreAddressListModelLists1.lists));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (cityId == null ? 0: cityId.hashCode());
    result = 31 * result + (cityName == null ? 0: cityName.hashCode());
    result = 31 * result + (lists == null ? 0: lists.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfflineStoreAddressListModelLists1 {\n");
    
    sb.append("  cityId: ").append(cityId).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  lists: ").append(lists).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
