/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * 订单简要信息
 **/
@ApiModel(description = "订单简要信息")
public class OrderBriefModel implements Serializable {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_logo")
  private String storeLogo = null;
  @SerializedName("rebate_amount_view")
  private String rebateAmountView = null;
  @SerializedName("consuming_amount_view")
  private String consumingAmountView = null;
  @SerializedName("is_effective")
  private String isEffective = null;
  @SerializedName("order_number")
  private String orderNumber = null;
  @SerializedName("order_time")
  private String orderTime = null;

  /**
   * 订单ID
   **/
  @ApiModelProperty(value = "订单ID")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 商家LOGO
   **/
  @ApiModelProperty(value = "商家LOGO")
  public String getStoreLogo() {
    return storeLogo;
  }
  public void setStoreLogo(String storeLogo) {
    this.storeLogo = storeLogo;
  }

  /**
   * 返利数额（文字说明）
   **/
  @ApiModelProperty(value = "返利数额（文字说明）")
  public String getRebateAmountView() {
    return rebateAmountView;
  }
  public void setRebateAmountView(String rebateAmountView) {
    this.rebateAmountView = rebateAmountView;
  }

  /**
   * 消费数额（文字说明）
   **/
  @ApiModelProperty(value = "消费数额（文字说明）")
  public String getConsumingAmountView() {
    return consumingAmountView;
  }
  public void setConsumingAmountView(String consumingAmountView) {
    this.consumingAmountView = consumingAmountView;
  }

  /**
   * 是否已生效 - 0：未生效 1：已生效
   **/
  @ApiModelProperty(value = "是否已生效 - 0：未生效 1：已生效")
  public String getIsEffective() {
    return isEffective;
  }
  public void setIsEffective(String isEffective) {
    this.isEffective = isEffective;
  }

  /**
   * 订单号
   **/
  @ApiModelProperty(value = "订单号")
  public String getOrderNumber() {
    return orderNumber;
  }
  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  /**
   * 下单时间
   **/
  @ApiModelProperty(value = "下单时间")
  public String getOrderTime() {
    return orderTime;
  }
  public void setOrderTime(String orderTime) {
    this.orderTime = orderTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderBriefModel orderBriefModel = (OrderBriefModel) o;
    return (id == null ? orderBriefModel.id == null : id.equals(orderBriefModel.id)) &&
        (storeId == null ? orderBriefModel.storeId == null : storeId.equals(orderBriefModel.storeId)) &&
        (storeName == null ? orderBriefModel.storeName == null : storeName.equals(orderBriefModel.storeName)) &&
        (storeLogo == null ? orderBriefModel.storeLogo == null : storeLogo.equals(orderBriefModel.storeLogo)) &&
        (rebateAmountView == null ? orderBriefModel.rebateAmountView == null : rebateAmountView.equals(orderBriefModel.rebateAmountView)) &&
        (consumingAmountView == null ? orderBriefModel.consumingAmountView == null : consumingAmountView.equals(orderBriefModel.consumingAmountView)) &&
        (isEffective == null ? orderBriefModel.isEffective == null : isEffective.equals(orderBriefModel.isEffective)) &&
        (orderNumber == null ? orderBriefModel.orderNumber == null : orderNumber.equals(orderBriefModel.orderNumber)) &&
        (orderTime == null ? orderBriefModel.orderTime == null : orderTime.equals(orderBriefModel.orderTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeLogo == null ? 0: storeLogo.hashCode());
    result = 31 * result + (rebateAmountView == null ? 0: rebateAmountView.hashCode());
    result = 31 * result + (consumingAmountView == null ? 0: consumingAmountView.hashCode());
    result = 31 * result + (isEffective == null ? 0: isEffective.hashCode());
    result = 31 * result + (orderNumber == null ? 0: orderNumber.hashCode());
    result = 31 * result + (orderTime == null ? 0: orderTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderBriefModel {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeLogo: ").append(storeLogo).append("\n");
    sb.append("  rebateAmountView: ").append(rebateAmountView).append("\n");
    sb.append("  consumingAmountView: ").append(consumingAmountView).append("\n");
    sb.append("  isEffective: ").append(isEffective).append("\n");
    sb.append("  orderNumber: ").append(orderNumber).append("\n");
    sb.append("  orderTime: ").append(orderTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
