/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.CouponModel;
import io.swagger.client.model.DealModel;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ReachedStoreIfModelData  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_description")
  private String storeDescription = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("has_rebate")
  private String hasRebate = null;
  @SerializedName("recommended_deals")
  private List<DealModel> recommendedDeals = null;
  @SerializedName("store_info_url")
  private String storeInfoUrl = null;
  @SerializedName("coupons")
  private List<CouponModel> coupons = null;
  @SerializedName("share_title")
  private String shareTitle = null;
  @SerializedName("share_content")
  private String shareContent = null;
  @SerializedName("share_content_weibo")
  private String shareContentWeibo = null;
  @SerializedName("share_url")
  private String shareUrl = null;
  @SerializedName("share_pic")
  private String sharePic = null;

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 返利商家介绍
   **/
  @ApiModelProperty(value = "返利商家介绍")
  public String getStoreDescription() {
    return storeDescription;
  }
  public void setStoreDescription(String storeDescription) {
    this.storeDescription = storeDescription;
  }

  /**
   * 显示的返利信息
   **/
  @ApiModelProperty(value = "显示的返利信息")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * 是否有返利 - 0：否 1：是
   **/
  @ApiModelProperty(value = "是否有返利 - 0：否 1：是")
  public String getHasRebate() {
    return hasRebate;
  }
  public void setHasRebate(String hasRebate) {
    this.hasRebate = hasRebate;
  }

  /**
   * 推荐优惠
   **/
  @ApiModelProperty(value = "推荐优惠")
  public List<DealModel> getRecommendedDeals() {
    return recommendedDeals;
  }
  public void setRecommendedDeals(List<DealModel> recommendedDeals) {
    this.recommendedDeals = recommendedDeals;
  }

  /**
   * 商家信息地址
   **/
  @ApiModelProperty(value = "商家信息地址")
  public String getStoreInfoUrl() {
    return storeInfoUrl;
  }
  public void setStoreInfoUrl(String storeInfoUrl) {
    this.storeInfoUrl = storeInfoUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CouponModel> getCoupons() {
    return coupons;
  }
  public void setCoupons(List<CouponModel> coupons) {
    this.coupons = coupons;
  }

  /**
   * 分享内容
   **/
  @ApiModelProperty(value = "分享内容")
  public String getShareTitle() {
    return shareTitle;
  }
  public void setShareTitle(String shareTitle) {
    this.shareTitle = shareTitle;
  }

  /**
   * 分享内容正文
   **/
  @ApiModelProperty(value = "分享内容正文")
  public String getShareContent() {
    return shareContent;
  }
  public void setShareContent(String shareContent) {
    this.shareContent = shareContent;
  }

  /**
   * 分享到微博的正文
   **/
  @ApiModelProperty(value = "分享到微博的正文")
  public String getShareContentWeibo() {
    return shareContentWeibo;
  }
  public void setShareContentWeibo(String shareContentWeibo) {
    this.shareContentWeibo = shareContentWeibo;
  }

  /**
   * 分享内容链接
   **/
  @ApiModelProperty(value = "分享内容链接")
  public String getShareUrl() {
    return shareUrl;
  }
  public void setShareUrl(String shareUrl) {
    this.shareUrl = shareUrl;
  }

  /**
   * 分享内容封面图片
   **/
  @ApiModelProperty(value = "分享内容封面图片")
  public String getSharePic() {
    return sharePic;
  }
  public void setSharePic(String sharePic) {
    this.sharePic = sharePic;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReachedStoreIfModelData reachedStoreIfModelData = (ReachedStoreIfModelData) o;
    return (storeId == null ? reachedStoreIfModelData.storeId == null : storeId.equals(reachedStoreIfModelData.storeId)) &&
        (storeName == null ? reachedStoreIfModelData.storeName == null : storeName.equals(reachedStoreIfModelData.storeName)) &&
        (storeDescription == null ? reachedStoreIfModelData.storeDescription == null : storeDescription.equals(reachedStoreIfModelData.storeDescription)) &&
        (rebateView == null ? reachedStoreIfModelData.rebateView == null : rebateView.equals(reachedStoreIfModelData.rebateView)) &&
        (hasRebate == null ? reachedStoreIfModelData.hasRebate == null : hasRebate.equals(reachedStoreIfModelData.hasRebate)) &&
        (recommendedDeals == null ? reachedStoreIfModelData.recommendedDeals == null : recommendedDeals.equals(reachedStoreIfModelData.recommendedDeals)) &&
        (storeInfoUrl == null ? reachedStoreIfModelData.storeInfoUrl == null : storeInfoUrl.equals(reachedStoreIfModelData.storeInfoUrl)) &&
        (coupons == null ? reachedStoreIfModelData.coupons == null : coupons.equals(reachedStoreIfModelData.coupons)) &&
        (shareTitle == null ? reachedStoreIfModelData.shareTitle == null : shareTitle.equals(reachedStoreIfModelData.shareTitle)) &&
        (shareContent == null ? reachedStoreIfModelData.shareContent == null : shareContent.equals(reachedStoreIfModelData.shareContent)) &&
        (shareContentWeibo == null ? reachedStoreIfModelData.shareContentWeibo == null : shareContentWeibo.equals(reachedStoreIfModelData.shareContentWeibo)) &&
        (shareUrl == null ? reachedStoreIfModelData.shareUrl == null : shareUrl.equals(reachedStoreIfModelData.shareUrl)) &&
        (sharePic == null ? reachedStoreIfModelData.sharePic == null : sharePic.equals(reachedStoreIfModelData.sharePic));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeDescription == null ? 0: storeDescription.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (hasRebate == null ? 0: hasRebate.hashCode());
    result = 31 * result + (recommendedDeals == null ? 0: recommendedDeals.hashCode());
    result = 31 * result + (storeInfoUrl == null ? 0: storeInfoUrl.hashCode());
    result = 31 * result + (coupons == null ? 0: coupons.hashCode());
    result = 31 * result + (shareTitle == null ? 0: shareTitle.hashCode());
    result = 31 * result + (shareContent == null ? 0: shareContent.hashCode());
    result = 31 * result + (shareContentWeibo == null ? 0: shareContentWeibo.hashCode());
    result = 31 * result + (shareUrl == null ? 0: shareUrl.hashCode());
    result = 31 * result + (sharePic == null ? 0: sharePic.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReachedStoreIfModelData {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeDescription: ").append(storeDescription).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  hasRebate: ").append(hasRebate).append("\n");
    sb.append("  recommendedDeals: ").append(recommendedDeals).append("\n");
    sb.append("  storeInfoUrl: ").append(storeInfoUrl).append("\n");
    sb.append("  coupons: ").append(coupons).append("\n");
    sb.append("  shareTitle: ").append(shareTitle).append("\n");
    sb.append("  shareContent: ").append(shareContent).append("\n");
    sb.append("  shareContentWeibo: ").append(shareContentWeibo).append("\n");
    sb.append("  shareUrl: ").append(shareUrl).append("\n");
    sb.append("  sharePic: ").append(sharePic).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
