/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class RebateMissedOrderDetailModel  {
  
  @SerializedName("order_id")
  private String orderId = null;
  @SerializedName("order_number")
  private String orderNumber = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_logo")
  private String storeLogo = null;
  @SerializedName("cost_view")
  private String costView = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("store_mail")
  private String storeMail = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("status_view")
  private String statusView = null;
  @SerializedName("order_pics")
  private List<String> orderPics = null;
  @SerializedName("feedback_time")
  private String feedbackTime = null;

  /**
   * 订单ID
   **/
  @ApiModelProperty(value = "订单ID")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  /**
   * 订单编号
   **/
  @ApiModelProperty(value = "订单编号")
  public String getOrderNumber() {
    return orderNumber;
  }
  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 商家LOGO
   **/
  @ApiModelProperty(value = "商家LOGO")
  public String getStoreLogo() {
    return storeLogo;
  }
  public void setStoreLogo(String storeLogo) {
    this.storeLogo = storeLogo;
  }

  /**
   * 消费金额（文字说明）
   **/
  @ApiModelProperty(value = "消费金额（文字说明）")
  public String getCostView() {
    return costView;
  }
  public void setCostView(String costView) {
    this.costView = costView;
  }

  /**
   * 返利金额（文字说明）
   **/
  @ApiModelProperty(value = "返利金额（文字说明）")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * 商家注册邮箱
   **/
  @ApiModelProperty(value = "商家注册邮箱")
  public String getStoreMail() {
    return storeMail;
  }
  public void setStoreMail(String storeMail) {
    this.storeMail = storeMail;
  }

  /**
   * 丢单反馈状态 - 0：已处理 1：处理中 2：待商家确认 3：无效丢单
   **/
  @ApiModelProperty(value = "丢单反馈状态 - 0：已处理 1：处理中 2：待商家确认 3：无效丢单")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * 丢单反馈状态(文字说明)
   **/
  @ApiModelProperty(value = "丢单反馈状态(文字说明)")
  public String getStatusView() {
    return statusView;
  }
  public void setStatusView(String statusView) {
    this.statusView = statusView;
  }

  /**
   * 订单截图
   **/
  @ApiModelProperty(value = "订单截图")
  public List<String> getOrderPics() {
    return orderPics;
  }
  public void setOrderPics(List<String> orderPics) {
    this.orderPics = orderPics;
  }

  /**
   * 反馈时间
   **/
  @ApiModelProperty(value = "反馈时间")
  public String getFeedbackTime() {
    return feedbackTime;
  }
  public void setFeedbackTime(String feedbackTime) {
    this.feedbackTime = feedbackTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RebateMissedOrderDetailModel rebateMissedOrderDetailModel = (RebateMissedOrderDetailModel) o;
    return (orderId == null ? rebateMissedOrderDetailModel.orderId == null : orderId.equals(rebateMissedOrderDetailModel.orderId)) &&
        (orderNumber == null ? rebateMissedOrderDetailModel.orderNumber == null : orderNumber.equals(rebateMissedOrderDetailModel.orderNumber)) &&
        (storeId == null ? rebateMissedOrderDetailModel.storeId == null : storeId.equals(rebateMissedOrderDetailModel.storeId)) &&
        (storeName == null ? rebateMissedOrderDetailModel.storeName == null : storeName.equals(rebateMissedOrderDetailModel.storeName)) &&
        (storeLogo == null ? rebateMissedOrderDetailModel.storeLogo == null : storeLogo.equals(rebateMissedOrderDetailModel.storeLogo)) &&
        (costView == null ? rebateMissedOrderDetailModel.costView == null : costView.equals(rebateMissedOrderDetailModel.costView)) &&
        (rebateView == null ? rebateMissedOrderDetailModel.rebateView == null : rebateView.equals(rebateMissedOrderDetailModel.rebateView)) &&
        (storeMail == null ? rebateMissedOrderDetailModel.storeMail == null : storeMail.equals(rebateMissedOrderDetailModel.storeMail)) &&
        (status == null ? rebateMissedOrderDetailModel.status == null : status.equals(rebateMissedOrderDetailModel.status)) &&
        (statusView == null ? rebateMissedOrderDetailModel.statusView == null : statusView.equals(rebateMissedOrderDetailModel.statusView)) &&
        (orderPics == null ? rebateMissedOrderDetailModel.orderPics == null : orderPics.equals(rebateMissedOrderDetailModel.orderPics)) &&
        (feedbackTime == null ? rebateMissedOrderDetailModel.feedbackTime == null : feedbackTime.equals(rebateMissedOrderDetailModel.feedbackTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (orderId == null ? 0: orderId.hashCode());
    result = 31 * result + (orderNumber == null ? 0: orderNumber.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeLogo == null ? 0: storeLogo.hashCode());
    result = 31 * result + (costView == null ? 0: costView.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (storeMail == null ? 0: storeMail.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (statusView == null ? 0: statusView.hashCode());
    result = 31 * result + (orderPics == null ? 0: orderPics.hashCode());
    result = 31 * result + (feedbackTime == null ? 0: feedbackTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RebateMissedOrderDetailModel {\n");
    
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  orderNumber: ").append(orderNumber).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeLogo: ").append(storeLogo).append("\n");
    sb.append("  costView: ").append(costView).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  storeMail: ").append(storeMail).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  statusView: ").append(statusView).append("\n");
    sb.append("  orderPics: ").append(orderPics).append("\n");
    sb.append("  feedbackTime: ").append(feedbackTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
