/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class RebateDetailModel  {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("type_view")
  private String typeView = null;
  @SerializedName("comment")
  private String comment = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("status_view")
  private String statusView = null;
  @SerializedName("rebate_amount")
  private String rebateAmount = null;
  @SerializedName("rebate_amount_view")
  private String rebateAmountView = null;
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("order_number")
  private String orderNumber = null;
  @SerializedName("effective_time")
  private String effectiveTime = null;

  /**
   * ID
   **/
  @ApiModelProperty(value = "ID")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * 返利类型 - 0:充值,1:支付运费,2:提现,3:返利, 4：下级返利, 5：满额赠送, 6：注册赠送，7：转运返现，8：推广注册赠送，9：赠送$1， 10：赠送$5，11:圣诞寻宝活动$2, 12:网站活动赠送,13:情报,14转运提现
   **/
  @ApiModelProperty(value = "返利类型 - 0:充值,1:支付运费,2:提现,3:返利, 4：下级返利, 5：满额赠送, 6：注册赠送，7：转运返现，8：推广注册赠送，9：赠送$1， 10：赠送$5，11:圣诞寻宝活动$2, 12:网站活动赠送,13:情报,14转运提现")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * 返利类型文字说明
   **/
  @ApiModelProperty(value = "返利类型文字说明")
  public String getTypeView() {
    return typeView;
  }
  public void setTypeView(String typeView) {
    this.typeView = typeView;
  }

  /**
   * 备注
   **/
  @ApiModelProperty(value = "备注")
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * 状态 - 0：已生效 1：未生效
   **/
  @ApiModelProperty(value = "状态 - 0：已生效 1：未生效")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * 状态文字说明
   **/
  @ApiModelProperty(value = "状态文字说明")
  public String getStatusView() {
    return statusView;
  }
  public void setStatusView(String statusView) {
    this.statusView = statusView;
  }

  /**
   * 返利金额
   **/
  @ApiModelProperty(value = "返利金额")
  public String getRebateAmount() {
    return rebateAmount;
  }
  public void setRebateAmount(String rebateAmount) {
    this.rebateAmount = rebateAmount;
  }

  /**
   * 返利金额文字描述 附带+号和货币符号
   **/
  @ApiModelProperty(value = "返利金额文字描述 附带+号和货币符号")
  public String getRebateAmountView() {
    return rebateAmountView;
  }
  public void setRebateAmountView(String rebateAmountView) {
    this.rebateAmountView = rebateAmountView;
  }

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 订单号
   **/
  @ApiModelProperty(value = "订单号")
  public String getOrderNumber() {
    return orderNumber;
  }
  public void setOrderNumber(String orderNumber) {
    this.orderNumber = orderNumber;
  }

  /**
   * 生效时间
   **/
  @ApiModelProperty(value = "生效时间")
  public String getEffectiveTime() {
    return effectiveTime;
  }
  public void setEffectiveTime(String effectiveTime) {
    this.effectiveTime = effectiveTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RebateDetailModel rebateDetailModel = (RebateDetailModel) o;
    return (id == null ? rebateDetailModel.id == null : id.equals(rebateDetailModel.id)) &&
        (type == null ? rebateDetailModel.type == null : type.equals(rebateDetailModel.type)) &&
        (typeView == null ? rebateDetailModel.typeView == null : typeView.equals(rebateDetailModel.typeView)) &&
        (comment == null ? rebateDetailModel.comment == null : comment.equals(rebateDetailModel.comment)) &&
        (status == null ? rebateDetailModel.status == null : status.equals(rebateDetailModel.status)) &&
        (statusView == null ? rebateDetailModel.statusView == null : statusView.equals(rebateDetailModel.statusView)) &&
        (rebateAmount == null ? rebateDetailModel.rebateAmount == null : rebateAmount.equals(rebateDetailModel.rebateAmount)) &&
        (rebateAmountView == null ? rebateDetailModel.rebateAmountView == null : rebateAmountView.equals(rebateDetailModel.rebateAmountView)) &&
        (storeId == null ? rebateDetailModel.storeId == null : storeId.equals(rebateDetailModel.storeId)) &&
        (storeName == null ? rebateDetailModel.storeName == null : storeName.equals(rebateDetailModel.storeName)) &&
        (orderNumber == null ? rebateDetailModel.orderNumber == null : orderNumber.equals(rebateDetailModel.orderNumber)) &&
        (effectiveTime == null ? rebateDetailModel.effectiveTime == null : effectiveTime.equals(rebateDetailModel.effectiveTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (type == null ? 0: type.hashCode());
    result = 31 * result + (typeView == null ? 0: typeView.hashCode());
    result = 31 * result + (comment == null ? 0: comment.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (statusView == null ? 0: statusView.hashCode());
    result = 31 * result + (rebateAmount == null ? 0: rebateAmount.hashCode());
    result = 31 * result + (rebateAmountView == null ? 0: rebateAmountView.hashCode());
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (orderNumber == null ? 0: orderNumber.hashCode());
    result = 31 * result + (effectiveTime == null ? 0: effectiveTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RebateDetailModel {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  typeView: ").append(typeView).append("\n");
    sb.append("  comment: ").append(comment).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  statusView: ").append(statusView).append("\n");
    sb.append("  rebateAmount: ").append(rebateAmount).append("\n");
    sb.append("  rebateAmountView: ").append(rebateAmountView).append("\n");
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  orderNumber: ").append(orderNumber).append("\n");
    sb.append("  effectiveTime: ").append(effectiveTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
