/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class RegionModel  {
  
  @SerializedName("region_id")
  private String regionId = null;
  @SerializedName("parent_id")
  private String parentId = null;
  @SerializedName("depth")
  private String depth = null;
  @SerializedName("region_name")
  private String regionName = null;

  /**
   * 地区ID
   **/
  @ApiModelProperty(value = "地区ID")
  public String getRegionId() {
    return regionId;
  }
  public void setRegionId(String regionId) {
    this.regionId = regionId;
  }

  /**
   * 父级ID
   **/
  @ApiModelProperty(value = "父级ID")
  public String getParentId() {
    return parentId;
  }
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  /**
   * 深度 - 0：省/直辖市 1：市 2：区/县
   **/
  @ApiModelProperty(value = "深度 - 0：省/直辖市 1：市 2：区/县")
  public String getDepth() {
    return depth;
  }
  public void setDepth(String depth) {
    this.depth = depth;
  }

  /**
   * 地区名称
   **/
  @ApiModelProperty(value = "地区名称")
  public String getRegionName() {
    return regionName;
  }
  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegionModel regionModel = (RegionModel) o;
    return (regionId == null ? regionModel.regionId == null : regionId.equals(regionModel.regionId)) &&
        (parentId == null ? regionModel.parentId == null : parentId.equals(regionModel.parentId)) &&
        (depth == null ? regionModel.depth == null : depth.equals(regionModel.depth)) &&
        (regionName == null ? regionModel.regionName == null : regionName.equals(regionModel.regionName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (regionId == null ? 0: regionId.hashCode());
    result = 31 * result + (parentId == null ? 0: parentId.hashCode());
    result = 31 * result + (depth == null ? 0: depth.hashCode());
    result = 31 * result + (regionName == null ? 0: regionName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegionModel {\n");
    
    sb.append("  regionId: ").append(regionId).append("\n");
    sb.append("  parentId: ").append(parentId).append("\n");
    sb.append("  depth: ").append(depth).append("\n");
    sb.append("  regionName: ").append(regionName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
