/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.4接口 
 *
 * OpenAPI spec version: 1.3 build20170809-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ShoppedStoresListModelDataRows  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_logo")
  private String storeLogo = null;
  @SerializedName("shopped_time")
  private String shoppedTime = null;

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 商家LOGO
   **/
  @ApiModelProperty(value = "商家LOGO")
  public String getStoreLogo() {
    return storeLogo;
  }
  public void setStoreLogo(String storeLogo) {
    this.storeLogo = storeLogo;
  }

  /**
   * 购物日期
   **/
  @ApiModelProperty(value = "购物日期")
  public String getShoppedTime() {
    return shoppedTime;
  }
  public void setShoppedTime(String shoppedTime) {
    this.shoppedTime = shoppedTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShoppedStoresListModelDataRows shoppedStoresListModelDataRows = (ShoppedStoresListModelDataRows) o;
    return (storeId == null ? shoppedStoresListModelDataRows.storeId == null : storeId.equals(shoppedStoresListModelDataRows.storeId)) &&
        (storeName == null ? shoppedStoresListModelDataRows.storeName == null : storeName.equals(shoppedStoresListModelDataRows.storeName)) &&
        (storeLogo == null ? shoppedStoresListModelDataRows.storeLogo == null : storeLogo.equals(shoppedStoresListModelDataRows.storeLogo)) &&
        (shoppedTime == null ? shoppedStoresListModelDataRows.shoppedTime == null : shoppedTime.equals(shoppedStoresListModelDataRows.shoppedTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeLogo == null ? 0: storeLogo.hashCode());
    result = 31 * result + (shoppedTime == null ? 0: shoppedTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShoppedStoresListModelDataRows {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeLogo: ").append(storeLogo).append("\n");
    sb.append("  shoppedTime: ").append(shoppedTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
