/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.5接口 
 *
 * OpenAPI spec version: 1.4 build20170928-4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SignedInRecordModel  {
  
  @SerializedName("journey")
  private String journey = null;
  @SerializedName("is_signed")
  private String isSigned = null;

  /**
   * 本月第几天
   **/
  @ApiModelProperty(value = "本月第几天")
  public String getJourney() {
    return journey;
  }
  public void setJourney(String journey) {
    this.journey = journey;
  }

  /**
   * 当天是否签到 - 0：未签 1：已签
   **/
  @ApiModelProperty(value = "当天是否签到 - 0：未签 1：已签")
  public String getIsSigned() {
    return isSigned;
  }
  public void setIsSigned(String isSigned) {
    this.isSigned = isSigned;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedInRecordModel signedInRecordModel = (SignedInRecordModel) o;
    return (journey == null ? signedInRecordModel.journey == null : journey.equals(signedInRecordModel.journey)) &&
        (isSigned == null ? signedInRecordModel.isSigned == null : isSigned.equals(signedInRecordModel.isSigned));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (journey == null ? 0: journey.hashCode());
    result = 31 * result + (isSigned == null ? 0: isSigned.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedInRecordModel {\n");
    
    sb.append("  journey: ").append(journey).append("\n");
    sb.append("  isSigned: ").append(isSigned).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
