/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.SingedInInfoModelDataCalendar;
import io.swagger.client.model.SlidePicModel;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SingedInInfoModelData  {
  
  @SerializedName("month_view")
  private String monthView = null;
  @SerializedName("is_signed_in")
  private String isSignedIn = null;
  @SerializedName("signed_in_days")
  private String signedInDays = null;
  @SerializedName("signed_golds_reward_view")
  private String signedGoldsRewardView = null;
  @SerializedName("talk_topic_id")
  private String talkTopicId = null;
  @SerializedName("talk_topic_title")
  private String talkTopicTitle = null;
  @SerializedName("replying_reward_view")
  private String replyingRewardView = null;
  @SerializedName("bottom_ad")
  private SlidePicModel bottomAd = null;
  @SerializedName("calendar")
  private List<SingedInInfoModelDataCalendar> calendar = null;

  /**
   * 月份（文字说明）
   **/
  @ApiModelProperty(value = "月份（文字说明）")
  public String getMonthView() {
    return monthView;
  }
  public void setMonthView(String monthView) {
    this.monthView = monthView;
  }

  /**
   * 今日是否已签到
   **/
  @ApiModelProperty(value = "今日是否已签到")
  public String getIsSignedIn() {
    return isSignedIn;
  }
  public void setIsSignedIn(String isSignedIn) {
    this.isSignedIn = isSignedIn;
  }

  /**
   * 连续签到天数
   **/
  @ApiModelProperty(value = "连续签到天数")
  public String getSignedInDays() {
    return signedInDays;
  }
  public void setSignedInDays(String signedInDays) {
    this.signedInDays = signedInDays;
  }

  /**
   * 今日签到获得的金币奖励数（文字说明）
   **/
  @ApiModelProperty(value = "今日签到获得的金币奖励数（文字说明）")
  public String getSignedGoldsRewardView() {
    return signedGoldsRewardView;
  }
  public void setSignedGoldsRewardView(String signedGoldsRewardView) {
    this.signedGoldsRewardView = signedGoldsRewardView;
  }

  /**
   * 今日话题帖子ID
   **/
  @ApiModelProperty(value = "今日话题帖子ID")
  public String getTalkTopicId() {
    return talkTopicId;
  }
  public void setTalkTopicId(String talkTopicId) {
    this.talkTopicId = talkTopicId;
  }

  /**
   * 今日话题标题
   **/
  @ApiModelProperty(value = "今日话题标题")
  public String getTalkTopicTitle() {
    return talkTopicTitle;
  }
  public void setTalkTopicTitle(String talkTopicTitle) {
    this.talkTopicTitle = talkTopicTitle;
  }

  /**
   * 回复今日话题帖可得的奖励（文字说明）
   **/
  @ApiModelProperty(value = "回复今日话题帖可得的奖励（文字说明）")
  public String getReplyingRewardView() {
    return replyingRewardView;
  }
  public void setReplyingRewardView(String replyingRewardView) {
    this.replyingRewardView = replyingRewardView;
  }

  /**
   * 底部横栏广告
   **/
  @ApiModelProperty(value = "底部横栏广告")
  public SlidePicModel getBottomAd() {
    return bottomAd;
  }
  public void setBottomAd(SlidePicModel bottomAd) {
    this.bottomAd = bottomAd;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SingedInInfoModelDataCalendar> getCalendar() {
    return calendar;
  }
  public void setCalendar(List<SingedInInfoModelDataCalendar> calendar) {
    this.calendar = calendar;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingedInInfoModelData singedInInfoModelData = (SingedInInfoModelData) o;
    return (monthView == null ? singedInInfoModelData.monthView == null : monthView.equals(singedInInfoModelData.monthView)) &&
        (isSignedIn == null ? singedInInfoModelData.isSignedIn == null : isSignedIn.equals(singedInInfoModelData.isSignedIn)) &&
        (signedInDays == null ? singedInInfoModelData.signedInDays == null : signedInDays.equals(singedInInfoModelData.signedInDays)) &&
        (signedGoldsRewardView == null ? singedInInfoModelData.signedGoldsRewardView == null : signedGoldsRewardView.equals(singedInInfoModelData.signedGoldsRewardView)) &&
        (talkTopicId == null ? singedInInfoModelData.talkTopicId == null : talkTopicId.equals(singedInInfoModelData.talkTopicId)) &&
        (talkTopicTitle == null ? singedInInfoModelData.talkTopicTitle == null : talkTopicTitle.equals(singedInInfoModelData.talkTopicTitle)) &&
        (replyingRewardView == null ? singedInInfoModelData.replyingRewardView == null : replyingRewardView.equals(singedInInfoModelData.replyingRewardView)) &&
        (bottomAd == null ? singedInInfoModelData.bottomAd == null : bottomAd.equals(singedInInfoModelData.bottomAd)) &&
        (calendar == null ? singedInInfoModelData.calendar == null : calendar.equals(singedInInfoModelData.calendar));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (monthView == null ? 0: monthView.hashCode());
    result = 31 * result + (isSignedIn == null ? 0: isSignedIn.hashCode());
    result = 31 * result + (signedInDays == null ? 0: signedInDays.hashCode());
    result = 31 * result + (signedGoldsRewardView == null ? 0: signedGoldsRewardView.hashCode());
    result = 31 * result + (talkTopicId == null ? 0: talkTopicId.hashCode());
    result = 31 * result + (talkTopicTitle == null ? 0: talkTopicTitle.hashCode());
    result = 31 * result + (replyingRewardView == null ? 0: replyingRewardView.hashCode());
    result = 31 * result + (bottomAd == null ? 0: bottomAd.hashCode());
    result = 31 * result + (calendar == null ? 0: calendar.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingedInInfoModelData {\n");
    
    sb.append("  monthView: ").append(monthView).append("\n");
    sb.append("  isSignedIn: ").append(isSignedIn).append("\n");
    sb.append("  signedInDays: ").append(signedInDays).append("\n");
    sb.append("  signedGoldsRewardView: ").append(signedGoldsRewardView).append("\n");
    sb.append("  talkTopicId: ").append(talkTopicId).append("\n");
    sb.append("  talkTopicTitle: ").append(talkTopicTitle).append("\n");
    sb.append("  replyingRewardView: ").append(replyingRewardView).append("\n");
    sb.append("  bottomAd: ").append(bottomAd).append("\n");
    sb.append("  calendar: ").append(calendar).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
