/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.SpiderDealModelOptions;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SpiderDealModelSkuList  {
  
  @SerializedName("style_id")
  private String styleId = null;
  @SerializedName("sku_id")
  private String skuId = null;
  @SerializedName("original_price")
  private String originalPrice = null;
  @SerializedName("now_price")
  private String nowPrice = null;
  @SerializedName("final_price")
  private String finalPrice = null;
  @SerializedName("stock_number")
  private String stockNumber = null;
  @SerializedName("options")
  private List<SpiderDealModelOptions> options = null;

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getStyleId() {
    return styleId;
  }
  public void setStyleId(String styleId) {
    this.styleId = styleId;
  }

  /**
   * skuId
   **/
  @ApiModelProperty(value = "skuId")
  public String getSkuId() {
    return skuId;
  }
  public void setSkuId(String skuId) {
    this.skuId = skuId;
  }

  /**
   * 原价
   **/
  @ApiModelProperty(value = "原价")
  public String getOriginalPrice() {
    return originalPrice;
  }
  public void setOriginalPrice(String originalPrice) {
    this.originalPrice = originalPrice;
  }

  /**
   * 现价
   **/
  @ApiModelProperty(value = "现价")
  public String getNowPrice() {
    return nowPrice;
  }
  public void setNowPrice(String nowPrice) {
    this.nowPrice = nowPrice;
  }

  /**
   * 到手价(币种为人民币)
   **/
  @ApiModelProperty(value = "到手价(币种为人民币)")
  public String getFinalPrice() {
    return finalPrice;
  }
  public void setFinalPrice(String finalPrice) {
    this.finalPrice = finalPrice;
  }

  /**
   * 库存数量
   **/
  @ApiModelProperty(value = "库存数量")
  public String getStockNumber() {
    return stockNumber;
  }
  public void setStockNumber(String stockNumber) {
    this.stockNumber = stockNumber;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SpiderDealModelOptions> getOptions() {
    return options;
  }
  public void setOptions(List<SpiderDealModelOptions> options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpiderDealModelSkuList spiderDealModelSkuList = (SpiderDealModelSkuList) o;
    return (styleId == null ? spiderDealModelSkuList.styleId == null : styleId.equals(spiderDealModelSkuList.styleId)) &&
        (skuId == null ? spiderDealModelSkuList.skuId == null : skuId.equals(spiderDealModelSkuList.skuId)) &&
        (originalPrice == null ? spiderDealModelSkuList.originalPrice == null : originalPrice.equals(spiderDealModelSkuList.originalPrice)) &&
        (nowPrice == null ? spiderDealModelSkuList.nowPrice == null : nowPrice.equals(spiderDealModelSkuList.nowPrice)) &&
        (finalPrice == null ? spiderDealModelSkuList.finalPrice == null : finalPrice.equals(spiderDealModelSkuList.finalPrice)) &&
        (stockNumber == null ? spiderDealModelSkuList.stockNumber == null : stockNumber.equals(spiderDealModelSkuList.stockNumber)) &&
        (options == null ? spiderDealModelSkuList.options == null : options.equals(spiderDealModelSkuList.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (styleId == null ? 0: styleId.hashCode());
    result = 31 * result + (skuId == null ? 0: skuId.hashCode());
    result = 31 * result + (originalPrice == null ? 0: originalPrice.hashCode());
    result = 31 * result + (nowPrice == null ? 0: nowPrice.hashCode());
    result = 31 * result + (finalPrice == null ? 0: finalPrice.hashCode());
    result = 31 * result + (stockNumber == null ? 0: stockNumber.hashCode());
    result = 31 * result + (options == null ? 0: options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpiderDealModelSkuList {\n");
    
    sb.append("  styleId: ").append(styleId).append("\n");
    sb.append("  skuId: ").append(skuId).append("\n");
    sb.append("  originalPrice: ").append(originalPrice).append("\n");
    sb.append("  nowPrice: ").append(nowPrice).append("\n");
    sb.append("  finalPrice: ").append(finalPrice).append("\n");
    sb.append("  stockNumber: ").append(stockNumber).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
