/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SpiderDealModelPropertiesList  {
  
  @SerializedName("sku_id")
  private String skuId = null;
  @SerializedName("price_point")
  private String pricePoint = null;
  @SerializedName("mail")
  private String mail = null;
  @SerializedName("remind_by_mail")
  private String remindByMail = null;
  @SerializedName("phone_number")
  private String phoneNumber = null;
  @SerializedName("remind_by_sms")
  private String remindBySms = null;

  /**
   * 当前SKUID
   **/
  @ApiModelProperty(value = "当前SKUID")
  public String getSkuId() {
    return skuId;
  }
  public void setSkuId(String skuId) {
    this.skuId = skuId;
  }

  /**
   * 降价到该金额以下提醒
   **/
  @ApiModelProperty(value = "降价到该金额以下提醒")
  public String getPricePoint() {
    return pricePoint;
  }
  public void setPricePoint(String pricePoint) {
    this.pricePoint = pricePoint;
  }

  /**
   * 用户邮箱地址
   **/
  @ApiModelProperty(value = "用户邮箱地址")
  public String getMail() {
    return mail;
  }
  public void setMail(String mail) {
    this.mail = mail;
  }

  /**
   * 通过邮件提醒的勾选状态 - 0：未选中 1：已选中
   **/
  @ApiModelProperty(value = "通过邮件提醒的勾选状态 - 0：未选中 1：已选中")
  public String getRemindByMail() {
    return remindByMail;
  }
  public void setRemindByMail(String remindByMail) {
    this.remindByMail = remindByMail;
  }

  /**
   * 手机号码
   **/
  @ApiModelProperty(value = "手机号码")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * 通过短信提醒的勾选状态 - 0：未选中 1：已选中
   **/
  @ApiModelProperty(value = "通过短信提醒的勾选状态 - 0：未选中 1：已选中")
  public String getRemindBySms() {
    return remindBySms;
  }
  public void setRemindBySms(String remindBySms) {
    this.remindBySms = remindBySms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpiderDealModelPropertiesList spiderDealModelPropertiesList = (SpiderDealModelPropertiesList) o;
    return (skuId == null ? spiderDealModelPropertiesList.skuId == null : skuId.equals(spiderDealModelPropertiesList.skuId)) &&
        (pricePoint == null ? spiderDealModelPropertiesList.pricePoint == null : pricePoint.equals(spiderDealModelPropertiesList.pricePoint)) &&
        (mail == null ? spiderDealModelPropertiesList.mail == null : mail.equals(spiderDealModelPropertiesList.mail)) &&
        (remindByMail == null ? spiderDealModelPropertiesList.remindByMail == null : remindByMail.equals(spiderDealModelPropertiesList.remindByMail)) &&
        (phoneNumber == null ? spiderDealModelPropertiesList.phoneNumber == null : phoneNumber.equals(spiderDealModelPropertiesList.phoneNumber)) &&
        (remindBySms == null ? spiderDealModelPropertiesList.remindBySms == null : remindBySms.equals(spiderDealModelPropertiesList.remindBySms));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (skuId == null ? 0: skuId.hashCode());
    result = 31 * result + (pricePoint == null ? 0: pricePoint.hashCode());
    result = 31 * result + (mail == null ? 0: mail.hashCode());
    result = 31 * result + (remindByMail == null ? 0: remindByMail.hashCode());
    result = 31 * result + (phoneNumber == null ? 0: phoneNumber.hashCode());
    result = 31 * result + (remindBySms == null ? 0: remindBySms.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpiderDealModelPropertiesList {\n");
    
    sb.append("  skuId: ").append(skuId).append("\n");
    sb.append("  pricePoint: ").append(pricePoint).append("\n");
    sb.append("  mail: ").append(mail).append("\n");
    sb.append("  remindByMail: ").append(remindByMail).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  remindBySms: ").append(remindBySms).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
