/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.SquiredModelLists;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SquiredModel  {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("width")
  private String width = null;
  @SerializedName("height")
  private String height = null;
  @SerializedName("show_type")
  private String showType = null;
  @SerializedName("lists")
  private List<SquiredModelLists> lists = null;

  /**
   * 九宫格栏目名称
   **/
  @ApiModelProperty(value = "九宫格栏目名称")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 九宫格显示宽度
   **/
  @ApiModelProperty(value = "九宫格显示宽度")
  public String getWidth() {
    return width;
  }
  public void setWidth(String width) {
    this.width = width;
  }

  /**
   * 九宫格显示高度
   **/
  @ApiModelProperty(value = "九宫格显示高度")
  public String getHeight() {
    return height;
  }
  public void setHeight(String height) {
    this.height = height;
  }

  /**
   * 九宫格显示样式
   **/
  @ApiModelProperty(value = "九宫格显示样式")
  public String getShowType() {
    return showType;
  }
  public void setShowType(String showType) {
    this.showType = showType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<SquiredModelLists> getLists() {
    return lists;
  }
  public void setLists(List<SquiredModelLists> lists) {
    this.lists = lists;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SquiredModel squiredModel = (SquiredModel) o;
    return (title == null ? squiredModel.title == null : title.equals(squiredModel.title)) &&
        (width == null ? squiredModel.width == null : width.equals(squiredModel.width)) &&
        (height == null ? squiredModel.height == null : height.equals(squiredModel.height)) &&
        (showType == null ? squiredModel.showType == null : showType.equals(squiredModel.showType)) &&
        (lists == null ? squiredModel.lists == null : lists.equals(squiredModel.lists));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (width == null ? 0: width.hashCode());
    result = 31 * result + (height == null ? 0: height.hashCode());
    result = 31 * result + (showType == null ? 0: showType.hashCode());
    result = 31 * result + (lists == null ? 0: lists.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SquiredModel {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  width: ").append(width).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  showType: ").append(showType).append("\n");
    sb.append("  lists: ").append(lists).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
