/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class StoreBriefModel  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("country_abbr")
  private String countryAbbr = null;
  @SerializedName("country_flag_pic")
  private String countryFlagPic = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("category_id")
  private String categoryId = null;
  @SerializedName("category_name")
  private String categoryName = null;

  /**
   * 商家ID
   **/
  @ApiModelProperty(value = "商家ID")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 国家缩写
   **/
  @ApiModelProperty(value = "国家缩写")
  public String getCountryAbbr() {
    return countryAbbr;
  }
  public void setCountryAbbr(String countryAbbr) {
    this.countryAbbr = countryAbbr;
  }

  /**
   * 国旗图片地址
   **/
  @ApiModelProperty(value = "国旗图片地址")
  public String getCountryFlagPic() {
    return countryFlagPic;
  }
  public void setCountryFlagPic(String countryFlagPic) {
    this.countryFlagPic = countryFlagPic;
  }

  /**
   * 返利信息（文字说明）
   **/
  @ApiModelProperty(value = "返利信息（文字说明）")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * 分类ID
   **/
  @ApiModelProperty(value = "分类ID")
  public String getCategoryId() {
    return categoryId;
  }
  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  /**
   * 分类名称
   **/
  @ApiModelProperty(value = "分类名称")
  public String getCategoryName() {
    return categoryName;
  }
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreBriefModel storeBriefModel = (StoreBriefModel) o;
    return (storeId == null ? storeBriefModel.storeId == null : storeId.equals(storeBriefModel.storeId)) &&
        (storeName == null ? storeBriefModel.storeName == null : storeName.equals(storeBriefModel.storeName)) &&
        (countryAbbr == null ? storeBriefModel.countryAbbr == null : countryAbbr.equals(storeBriefModel.countryAbbr)) &&
        (countryFlagPic == null ? storeBriefModel.countryFlagPic == null : countryFlagPic.equals(storeBriefModel.countryFlagPic)) &&
        (rebateView == null ? storeBriefModel.rebateView == null : rebateView.equals(storeBriefModel.rebateView)) &&
        (categoryId == null ? storeBriefModel.categoryId == null : categoryId.equals(storeBriefModel.categoryId)) &&
        (categoryName == null ? storeBriefModel.categoryName == null : categoryName.equals(storeBriefModel.categoryName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (countryAbbr == null ? 0: countryAbbr.hashCode());
    result = 31 * result + (countryFlagPic == null ? 0: countryFlagPic.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (categoryId == null ? 0: categoryId.hashCode());
    result = 31 * result + (categoryName == null ? 0: categoryName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreBriefModel {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  countryAbbr: ").append(countryAbbr).append("\n");
    sb.append("  countryFlagPic: ").append(countryFlagPic).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  categoryId: ").append(categoryId).append("\n");
    sb.append("  categoryName: ").append(categoryName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
