/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class StoreWithDealsModelDeals  {
  
  @SerializedName("deal_id")
  private String dealId = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("deal_pic")
  private String dealPic = null;
  @SerializedName("price_view")
  private String priceView = null;
  @SerializedName("has_rebate")
  private String hasRebate = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("left_time")
  private String leftTime = null;

  /**
   * 优惠ID
   **/
  @ApiModelProperty(value = "优惠ID")
  public String getDealId() {
    return dealId;
  }
  public void setDealId(String dealId) {
    this.dealId = dealId;
  }

  /**
   * 优惠标题
   **/
  @ApiModelProperty(value = "优惠标题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 优惠图片
   **/
  @ApiModelProperty(value = "优惠图片")
  public String getDealPic() {
    return dealPic;
  }
  public void setDealPic(String dealPic) {
    this.dealPic = dealPic;
  }

  /**
   * 显示价格
   **/
  @ApiModelProperty(value = "显示价格")
  public String getPriceView() {
    return priceView;
  }
  public void setPriceView(String priceView) {
    this.priceView = priceView;
  }

  /**
   * 是否有返利
   **/
  @ApiModelProperty(value = "是否有返利")
  public String getHasRebate() {
    return hasRebate;
  }
  public void setHasRebate(String hasRebate) {
    this.hasRebate = hasRebate;
  }

  /**
   * 显示的返利信息
   **/
  @ApiModelProperty(value = "显示的返利信息")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * 显示的返利信息
   **/
  @ApiModelProperty(value = "显示的返利信息")
  public String getLeftTime() {
    return leftTime;
  }
  public void setLeftTime(String leftTime) {
    this.leftTime = leftTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoreWithDealsModelDeals storeWithDealsModelDeals = (StoreWithDealsModelDeals) o;
    return (dealId == null ? storeWithDealsModelDeals.dealId == null : dealId.equals(storeWithDealsModelDeals.dealId)) &&
        (title == null ? storeWithDealsModelDeals.title == null : title.equals(storeWithDealsModelDeals.title)) &&
        (dealPic == null ? storeWithDealsModelDeals.dealPic == null : dealPic.equals(storeWithDealsModelDeals.dealPic)) &&
        (priceView == null ? storeWithDealsModelDeals.priceView == null : priceView.equals(storeWithDealsModelDeals.priceView)) &&
        (hasRebate == null ? storeWithDealsModelDeals.hasRebate == null : hasRebate.equals(storeWithDealsModelDeals.hasRebate)) &&
        (rebateView == null ? storeWithDealsModelDeals.rebateView == null : rebateView.equals(storeWithDealsModelDeals.rebateView)) &&
        (leftTime == null ? storeWithDealsModelDeals.leftTime == null : leftTime.equals(storeWithDealsModelDeals.leftTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (dealId == null ? 0: dealId.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (dealPic == null ? 0: dealPic.hashCode());
    result = 31 * result + (priceView == null ? 0: priceView.hashCode());
    result = 31 * result + (hasRebate == null ? 0: hasRebate.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (leftTime == null ? 0: leftTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreWithDealsModelDeals {\n");
    
    sb.append("  dealId: ").append(dealId).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  dealPic: ").append(dealPic).append("\n");
    sb.append("  priceView: ").append(priceView).append("\n");
    sb.append("  hasRebate: ").append(hasRebate).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  leftTime: ").append(leftTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
