/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class SystemSettingsModelDataActivity  {
  
  @SerializedName("is_enabled")
  private String isEnabled = null;
  @SerializedName("key")
  private String key = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("url")
  private String url = null;

  /**
   * 活动是否开启 - 0：未开启 1：已开启
   **/
  @ApiModelProperty(value = "活动是否开启 - 0：未开启 1：已开启")
  public String getIsEnabled() {
    return isEnabled;
  }
  public void setIsEnabled(String isEnabled) {
    this.isEnabled = isEnabled;
  }

  /**
   * 活动标示名 - 当前支持的活动 black_friday: 黑五 anniversary: 周年庆
   **/
  @ApiModelProperty(value = "活动标示名 - 当前支持的活动 black_friday: 黑五 anniversary: 周年庆")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   * 活动名称（文案）
   **/
  @ApiModelProperty(value = "活动名称（文案）")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * 活动URL
   **/
  @ApiModelProperty(value = "活动URL")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemSettingsModelDataActivity systemSettingsModelDataActivity = (SystemSettingsModelDataActivity) o;
    return (isEnabled == null ? systemSettingsModelDataActivity.isEnabled == null : isEnabled.equals(systemSettingsModelDataActivity.isEnabled)) &&
        (key == null ? systemSettingsModelDataActivity.key == null : key.equals(systemSettingsModelDataActivity.key)) &&
        (name == null ? systemSettingsModelDataActivity.name == null : name.equals(systemSettingsModelDataActivity.name)) &&
        (url == null ? systemSettingsModelDataActivity.url == null : url.equals(systemSettingsModelDataActivity.url));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (isEnabled == null ? 0: isEnabled.hashCode());
    result = 31 * result + (key == null ? 0: key.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (url == null ? 0: url.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemSettingsModelDataActivity {\n");
    
    sb.append("  isEnabled: ").append(isEnabled).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
