/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ThirdPartyPlatformModel  {
  
  @SerializedName("tpp_id")
  private String tppId = null;
  @SerializedName("tpp_name")
  private String tppName = null;
  @SerializedName("tpp_key")
  private String tppKey = null;
  @SerializedName("icon")
  private String icon = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("binded")
  private String binded = null;

  /**
   * 第三方平台ID
   **/
  @ApiModelProperty(value = "第三方平台ID")
  public String getTppId() {
    return tppId;
  }
  public void setTppId(String tppId) {
    this.tppId = tppId;
  }

  /**
   * 第三方平台名称
   **/
  @ApiModelProperty(value = "第三方平台名称")
  public String getTppName() {
    return tppName;
  }
  public void setTppName(String tppName) {
    this.tppName = tppName;
  }

  /**
   * 第三方平台key
   **/
  @ApiModelProperty(value = "第三方平台key")
  public String getTppKey() {
    return tppKey;
  }
  public void setTppKey(String tppKey) {
    this.tppKey = tppKey;
  }

  /**
   * 第三方平台图标
   **/
  @ApiModelProperty(value = "第三方平台图标")
  public String getIcon() {
    return icon;
  }
  public void setIcon(String icon) {
    this.icon = icon;
  }

  /**
   * 第三方平台状态 - 0：正常 1：不可用
   **/
  @ApiModelProperty(value = "第三方平台状态 - 0：正常 1：不可用")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * 用户第三方账号状态 - 0：未绑定 1：已绑定
   **/
  @ApiModelProperty(value = "用户第三方账号状态 - 0：未绑定 1：已绑定")
  public String getBinded() {
    return binded;
  }
  public void setBinded(String binded) {
    this.binded = binded;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThirdPartyPlatformModel thirdPartyPlatformModel = (ThirdPartyPlatformModel) o;
    return (tppId == null ? thirdPartyPlatformModel.tppId == null : tppId.equals(thirdPartyPlatformModel.tppId)) &&
        (tppName == null ? thirdPartyPlatformModel.tppName == null : tppName.equals(thirdPartyPlatformModel.tppName)) &&
        (tppKey == null ? thirdPartyPlatformModel.tppKey == null : tppKey.equals(thirdPartyPlatformModel.tppKey)) &&
        (icon == null ? thirdPartyPlatformModel.icon == null : icon.equals(thirdPartyPlatformModel.icon)) &&
        (status == null ? thirdPartyPlatformModel.status == null : status.equals(thirdPartyPlatformModel.status)) &&
        (binded == null ? thirdPartyPlatformModel.binded == null : binded.equals(thirdPartyPlatformModel.binded));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (tppId == null ? 0: tppId.hashCode());
    result = 31 * result + (tppName == null ? 0: tppName.hashCode());
    result = 31 * result + (tppKey == null ? 0: tppKey.hashCode());
    result = 31 * result + (icon == null ? 0: icon.hashCode());
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (binded == null ? 0: binded.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThirdPartyPlatformModel {\n");
    
    sb.append("  tppId: ").append(tppId).append("\n");
    sb.append("  tppName: ").append(tppName).append("\n");
    sb.append("  tppKey: ").append(tppKey).append("\n");
    sb.append("  icon: ").append(icon).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  binded: ").append(binded).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
