/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP5.4接口 
 *
 * OpenAPI spec version: 1.3 build20170808-1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class TopicsRepliesListModelDataSource  {
  
  @SerializedName("author_name")
  private String authorName = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("pid")
  private String pid = null;
  @SerializedName("floor_num")
  private String floorNum = null;

  /**
   * 引用内容的作者
   **/
  @ApiModelProperty(value = "引用内容的作者")
  public String getAuthorName() {
    return authorName;
  }
  public void setAuthorName(String authorName) {
    this.authorName = authorName;
  }

  /**
   * 主题标题
   **/
  @ApiModelProperty(value = "主题标题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 回复目标ID
   **/
  @ApiModelProperty(value = "回复目标ID")
  public String getPid() {
    return pid;
  }
  public void setPid(String pid) {
    this.pid = pid;
  }

  /**
   * 引用回复的楼层
   **/
  @ApiModelProperty(value = "引用回复的楼层")
  public String getFloorNum() {
    return floorNum;
  }
  public void setFloorNum(String floorNum) {
    this.floorNum = floorNum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopicsRepliesListModelDataSource topicsRepliesListModelDataSource = (TopicsRepliesListModelDataSource) o;
    return (authorName == null ? topicsRepliesListModelDataSource.authorName == null : authorName.equals(topicsRepliesListModelDataSource.authorName)) &&
        (title == null ? topicsRepliesListModelDataSource.title == null : title.equals(topicsRepliesListModelDataSource.title)) &&
        (pid == null ? topicsRepliesListModelDataSource.pid == null : pid.equals(topicsRepliesListModelDataSource.pid)) &&
        (floorNum == null ? topicsRepliesListModelDataSource.floorNum == null : floorNum.equals(topicsRepliesListModelDataSource.floorNum));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (authorName == null ? 0: authorName.hashCode());
    result = 31 * result + (title == null ? 0: title.hashCode());
    result = 31 * result + (pid == null ? 0: pid.hashCode());
    result = 31 * result + (floorNum == null ? 0: floorNum.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopicsRepliesListModelDataSource {\n");
    
    sb.append("  authorName: ").append(authorName).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  pid: ").append(pid).append("\n");
    sb.append("  floorNum: ").append(floorNum).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
