/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/> APP旧接口迭代 
 *
 * OpenAPI spec version: 1.6 build20171114-1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.TppLoginFailedModelData;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class TppLoginFailedModel  {
  
  @SerializedName("code")
  private String code = null;
  @SerializedName("msg")
  private String msg = null;
  @SerializedName("data")
  private TppLoginFailedModelData data = null;

  /**
   * 2101:使用第三方平台登录成功，但需要绑定55帐号;其他错误代码：参见WIKI
   **/
  @ApiModelProperty(value = "2101:使用第三方平台登录成功，但需要绑定55帐号;其他错误代码：参见WIKI")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }

  /**
   * 失败信息
   **/
  @ApiModelProperty(value = "失败信息")
  public String getMsg() {
    return msg;
  }
  public void setMsg(String msg) {
    this.msg = msg;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TppLoginFailedModelData getData() {
    return data;
  }
  public void setData(TppLoginFailedModelData data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TppLoginFailedModel tppLoginFailedModel = (TppLoginFailedModel) o;
    return (code == null ? tppLoginFailedModel.code == null : code.equals(tppLoginFailedModel.code)) &&
        (msg == null ? tppLoginFailedModel.msg == null : msg.equals(tppLoginFailedModel.msg)) &&
        (data == null ? tppLoginFailedModel.data == null : data.equals(tppLoginFailedModel.data));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (code == null ? 0: code.hashCode());
    result = 31 * result + (msg == null ? 0: msg.hashCode());
    result = 31 * result + (data == null ? 0: data.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TppLoginFailedModel {\n");
    
    sb.append("  code: ").append(code).append("\n");
    sb.append("  msg: ").append(msg).append("\n");
    sb.append("  data: ").append(data).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
