/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserWithdrawingIndexModel  {
  
  @SerializedName("balance")
  private String balance = null;
  @SerializedName("minimum_amount")
  private String minimumAmount = null;
  @SerializedName("comment")
  private String comment = null;

  /**
   * 可用余额
   **/
  @ApiModelProperty(value = "可用余额")
  public String getBalance() {
    return balance;
  }
  public void setBalance(String balance) {
    this.balance = balance;
  }

  /**
   * 最低提现金额
   **/
  @ApiModelProperty(value = "最低提现金额")
  public String getMinimumAmount() {
    return minimumAmount;
  }
  public void setMinimumAmount(String minimumAmount) {
    this.minimumAmount = minimumAmount;
  }

  /**
   * 说明信息
   **/
  @ApiModelProperty(value = "说明信息")
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWithdrawingIndexModel userWithdrawingIndexModel = (UserWithdrawingIndexModel) o;
    return (balance == null ? userWithdrawingIndexModel.balance == null : balance.equals(userWithdrawingIndexModel.balance)) &&
        (minimumAmount == null ? userWithdrawingIndexModel.minimumAmount == null : minimumAmount.equals(userWithdrawingIndexModel.minimumAmount)) &&
        (comment == null ? userWithdrawingIndexModel.comment == null : comment.equals(userWithdrawingIndexModel.comment));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (balance == null ? 0: balance.hashCode());
    result = 31 * result + (minimumAmount == null ? 0: minimumAmount.hashCode());
    result = 31 * result + (comment == null ? 0: comment.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWithdrawingIndexModel {\n");
    
    sb.append("  balance: ").append(balance).append("\n");
    sb.append("  minimumAmount: ").append(minimumAmount).append("\n");
    sb.append("  comment: ").append(comment).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
