/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserBriefInfoModel  {
  
  @SerializedName("uid")
  private String uid = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("balance")
  private String balance = null;
  @SerializedName("freezed_balance")
  private String freezedBalance = null;
  @SerializedName("balance_view")
  private String balanceView = null;
  @SerializedName("freezed_balance_view")
  private String freezedBalanceView = null;
  @SerializedName("is_vip")
  private String isVip = null;
  @SerializedName("has_binded_phone_number")
  private String hasBindedPhoneNumber = null;
  @SerializedName("phone_number")
  private String phoneNumber = null;
  @SerializedName("hidden_parts_phone_number")
  private String hiddenPartsPhoneNumber = null;
  @SerializedName("has_new_msg")
  private String hasNewMsg = null;

  /**
   * 用户ID
   **/
  @ApiModelProperty(value = "用户ID")
  public String getUid() {
    return uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   * 用户名
   **/
  @ApiModelProperty(value = "用户名")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * 用户头像地址
   **/
  @ApiModelProperty(value = "用户头像地址")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * 可用金额
   **/
  @ApiModelProperty(value = "可用金额")
  public String getBalance() {
    return balance;
  }
  public void setBalance(String balance) {
    this.balance = balance;
  }

  /**
   * 待可用金额
   **/
  @ApiModelProperty(value = "待可用金额")
  public String getFreezedBalance() {
    return freezedBalance;
  }
  public void setFreezedBalance(String freezedBalance) {
    this.freezedBalance = freezedBalance;
  }

  /**
   * 可用余额(文字描述)
   **/
  @ApiModelProperty(value = "可用余额(文字描述)")
  public String getBalanceView() {
    return balanceView;
  }
  public void setBalanceView(String balanceView) {
    this.balanceView = balanceView;
  }

  /**
   * 待可用余额(文字描述)
   **/
  @ApiModelProperty(value = "待可用余额(文字描述)")
  public String getFreezedBalanceView() {
    return freezedBalanceView;
  }
  public void setFreezedBalanceView(String freezedBalanceView) {
    this.freezedBalanceView = freezedBalanceView;
  }

  /**
   * 是否是VIP - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否是VIP - 0为否 1为是")
  public String getIsVip() {
    return isVip;
  }
  public void setIsVip(String isVip) {
    this.isVip = isVip;
  }

  /**
   * 是否已绑定手机 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否已绑定手机 - 0为否 1为是")
  public String getHasBindedPhoneNumber() {
    return hasBindedPhoneNumber;
  }
  public void setHasBindedPhoneNumber(String hasBindedPhoneNumber) {
    this.hasBindedPhoneNumber = hasBindedPhoneNumber;
  }

  /**
   * 正常的手机号内容
   **/
  @ApiModelProperty(value = "正常的手机号内容")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * 隐藏了部分内容的手机号 用于敏感操作时的提示显示 例:189****1262
   **/
  @ApiModelProperty(value = "隐藏了部分内容的手机号 用于敏感操作时的提示显示 例:189****1262")
  public String getHiddenPartsPhoneNumber() {
    return hiddenPartsPhoneNumber;
  }
  public void setHiddenPartsPhoneNumber(String hiddenPartsPhoneNumber) {
    this.hiddenPartsPhoneNumber = hiddenPartsPhoneNumber;
  }

  /**
   * 是否有新消息 - 0：否 1：是
   **/
  @ApiModelProperty(value = "是否有新消息 - 0：否 1：是")
  public String getHasNewMsg() {
    return hasNewMsg;
  }
  public void setHasNewMsg(String hasNewMsg) {
    this.hasNewMsg = hasNewMsg;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserBriefInfoModel userBriefInfoModel = (UserBriefInfoModel) o;
    return (uid == null ? userBriefInfoModel.uid == null : uid.equals(userBriefInfoModel.uid)) &&
        (username == null ? userBriefInfoModel.username == null : username.equals(userBriefInfoModel.username)) &&
        (avatar == null ? userBriefInfoModel.avatar == null : avatar.equals(userBriefInfoModel.avatar)) &&
        (balance == null ? userBriefInfoModel.balance == null : balance.equals(userBriefInfoModel.balance)) &&
        (freezedBalance == null ? userBriefInfoModel.freezedBalance == null : freezedBalance.equals(userBriefInfoModel.freezedBalance)) &&
        (balanceView == null ? userBriefInfoModel.balanceView == null : balanceView.equals(userBriefInfoModel.balanceView)) &&
        (freezedBalanceView == null ? userBriefInfoModel.freezedBalanceView == null : freezedBalanceView.equals(userBriefInfoModel.freezedBalanceView)) &&
        (isVip == null ? userBriefInfoModel.isVip == null : isVip.equals(userBriefInfoModel.isVip)) &&
        (hasBindedPhoneNumber == null ? userBriefInfoModel.hasBindedPhoneNumber == null : hasBindedPhoneNumber.equals(userBriefInfoModel.hasBindedPhoneNumber)) &&
        (phoneNumber == null ? userBriefInfoModel.phoneNumber == null : phoneNumber.equals(userBriefInfoModel.phoneNumber)) &&
        (hiddenPartsPhoneNumber == null ? userBriefInfoModel.hiddenPartsPhoneNumber == null : hiddenPartsPhoneNumber.equals(userBriefInfoModel.hiddenPartsPhoneNumber)) &&
        (hasNewMsg == null ? userBriefInfoModel.hasNewMsg == null : hasNewMsg.equals(userBriefInfoModel.hasNewMsg));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (uid == null ? 0: uid.hashCode());
    result = 31 * result + (username == null ? 0: username.hashCode());
    result = 31 * result + (avatar == null ? 0: avatar.hashCode());
    result = 31 * result + (balance == null ? 0: balance.hashCode());
    result = 31 * result + (freezedBalance == null ? 0: freezedBalance.hashCode());
    result = 31 * result + (balanceView == null ? 0: balanceView.hashCode());
    result = 31 * result + (freezedBalanceView == null ? 0: freezedBalanceView.hashCode());
    result = 31 * result + (isVip == null ? 0: isVip.hashCode());
    result = 31 * result + (hasBindedPhoneNumber == null ? 0: hasBindedPhoneNumber.hashCode());
    result = 31 * result + (phoneNumber == null ? 0: phoneNumber.hashCode());
    result = 31 * result + (hiddenPartsPhoneNumber == null ? 0: hiddenPartsPhoneNumber.hashCode());
    result = 31 * result + (hasNewMsg == null ? 0: hasNewMsg.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserBriefInfoModel {\n");
    
    sb.append("  uid: ").append(uid).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  balance: ").append(balance).append("\n");
    sb.append("  freezedBalance: ").append(freezedBalance).append("\n");
    sb.append("  balanceView: ").append(balanceView).append("\n");
    sb.append("  freezedBalanceView: ").append(freezedBalanceView).append("\n");
    sb.append("  isVip: ").append(isVip).append("\n");
    sb.append("  hasBindedPhoneNumber: ").append(hasBindedPhoneNumber).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  hiddenPartsPhoneNumber: ").append(hiddenPartsPhoneNumber).append("\n");
    sb.append("  hasNewMsg: ").append(hasNewMsg).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
