/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.UserInfoModelRegion;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class UserInfoModel  {
  
  @SerializedName("uid")
  private String uid = null;
  @SerializedName("username")
  private String username = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("user_level")
  private String userLevel = null;
  @SerializedName("group_name")
  private String groupName = null;
  @SerializedName("sex")
  private String sex = null;
  @SerializedName("signature")
  private String signature = null;
  @SerializedName("area_code")
  private String areaCode = null;
  @SerializedName("phone_number")
  private String phoneNumber = null;
  @SerializedName("hidden_parts_phone_number")
  private String hiddenPartsPhoneNumber = null;
  @SerializedName("mail")
  private String mail = null;
  @SerializedName("privilege_url")
  private String privilegeUrl = null;
  @SerializedName("balance")
  private String balance = null;
  @SerializedName("freezed_balance")
  private String freezedBalance = null;
  @SerializedName("balance_view")
  private String balanceView = null;
  @SerializedName("freezed_balance_view")
  private String freezedBalanceView = null;
  @SerializedName("phone_number_is_unique")
  private String phoneNumberIsUnique = null;
  @SerializedName("has_binded_phone_number")
  private String hasBindedPhoneNumber = null;
  @SerializedName("has_setted_withdrawing_pwd")
  private String hasSettedWithdrawingPwd = null;
  @SerializedName("has_withdrawing_account")
  private String hasWithdrawingAccount = null;
  @SerializedName("has_signed_in")
  private String hasSignedIn = null;
  @SerializedName("has_new_msg")
  private String hasNewMsg = null;
  @SerializedName("new_msgs_count")
  private String newMsgsCount = null;
  @SerializedName("praise_count")
  private String praiseCount = null;
  @SerializedName("golds_count")
  private String goldsCount = null;
  @SerializedName("points_count")
  private String pointsCount = null;
  @SerializedName("is_vip")
  private String isVip = null;
  @SerializedName("vip_exclusive_items_url")
  private String vipExclusiveItemsUrl = null;
  @SerializedName("region")
  private UserInfoModelRegion region = null;

  /**
   * 用户ID
   **/
  @ApiModelProperty(value = "用户ID")
  public String getUid() {
    return uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }

  /**
   * 用户名
   **/
  @ApiModelProperty(value = "用户名")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * 用户头像地址
   **/
  @ApiModelProperty(value = "用户头像地址")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * 用户等级（级数）
   **/
  @ApiModelProperty(value = "用户等级（级数）")
  public String getUserLevel() {
    return userLevel;
  }
  public void setUserLevel(String userLevel) {
    this.userLevel = userLevel;
  }

  /**
   * 用户组名
   **/
  @ApiModelProperty(value = "用户组名")
  public String getGroupName() {
    return groupName;
  }
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  /**
   * 性别 - 0：保密 1：男 2：女
   **/
  @ApiModelProperty(value = "性别 - 0：保密 1：男 2：女")
  public String getSex() {
    return sex;
  }
  public void setSex(String sex) {
    this.sex = sex;
  }

  /**
   * 用户个人签名内容
   **/
  @ApiModelProperty(value = "用户个人签名内容")
  public String getSignature() {
    return signature;
  }
  public void setSignature(String signature) {
    this.signature = signature;
  }

  /**
   * 手机号码的国际区号
   **/
  @ApiModelProperty(value = "手机号码的国际区号")
  public String getAreaCode() {
    return areaCode;
  }
  public void setAreaCode(String areaCode) {
    this.areaCode = areaCode;
  }

  /**
   * 手机号码
   **/
  @ApiModelProperty(value = "手机号码")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * 隐藏了部分内容的手机号 用于敏感操作时的提示显示 例:189****1262
   **/
  @ApiModelProperty(value = "隐藏了部分内容的手机号 用于敏感操作时的提示显示 例:189****1262")
  public String getHiddenPartsPhoneNumber() {
    return hiddenPartsPhoneNumber;
  }
  public void setHiddenPartsPhoneNumber(String hiddenPartsPhoneNumber) {
    this.hiddenPartsPhoneNumber = hiddenPartsPhoneNumber;
  }

  /**
   * 邮箱地址
   **/
  @ApiModelProperty(value = "邮箱地址")
  public String getMail() {
    return mail;
  }
  public void setMail(String mail) {
    this.mail = mail;
  }

  /**
   * VIP专享权益链接
   **/
  @ApiModelProperty(value = "VIP专享权益链接")
  public String getPrivilegeUrl() {
    return privilegeUrl;
  }
  public void setPrivilegeUrl(String privilegeUrl) {
    this.privilegeUrl = privilegeUrl;
  }

  /**
   * 可用余额
   **/
  @ApiModelProperty(value = "可用余额")
  public String getBalance() {
    return balance;
  }
  public void setBalance(String balance) {
    this.balance = balance;
  }

  /**
   * 待可用余额
   **/
  @ApiModelProperty(value = "待可用余额")
  public String getFreezedBalance() {
    return freezedBalance;
  }
  public void setFreezedBalance(String freezedBalance) {
    this.freezedBalance = freezedBalance;
  }

  /**
   * 可用余额(文字描述)
   **/
  @ApiModelProperty(value = "可用余额(文字描述)")
  public String getBalanceView() {
    return balanceView;
  }
  public void setBalanceView(String balanceView) {
    this.balanceView = balanceView;
  }

  /**
   * 待可用余额(文字描述)
   **/
  @ApiModelProperty(value = "待可用余额(文字描述)")
  public String getFreezedBalanceView() {
    return freezedBalanceView;
  }
  public void setFreezedBalanceView(String freezedBalanceView) {
    this.freezedBalanceView = freezedBalanceView;
  }

  /**
   * 手机号码是否是唯一 - 0为否 1为是
   **/
  @ApiModelProperty(value = "手机号码是否是唯一 - 0为否 1为是")
  public String getPhoneNumberIsUnique() {
    return phoneNumberIsUnique;
  }
  public void setPhoneNumberIsUnique(String phoneNumberIsUnique) {
    this.phoneNumberIsUnique = phoneNumberIsUnique;
  }

  /**
   * 是否已绑定手机 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否已绑定手机 - 0为否 1为是")
  public String getHasBindedPhoneNumber() {
    return hasBindedPhoneNumber;
  }
  public void setHasBindedPhoneNumber(String hasBindedPhoneNumber) {
    this.hasBindedPhoneNumber = hasBindedPhoneNumber;
  }

  /**
   * 是否已设置提现密码 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否已设置提现密码 - 0为否 1为是")
  public String getHasSettedWithdrawingPwd() {
    return hasSettedWithdrawingPwd;
  }
  public void setHasSettedWithdrawingPwd(String hasSettedWithdrawingPwd) {
    this.hasSettedWithdrawingPwd = hasSettedWithdrawingPwd;
  }

  /**
   * 是否已绑定提现账户 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否已绑定提现账户 - 0为否 1为是")
  public String getHasWithdrawingAccount() {
    return hasWithdrawingAccount;
  }
  public void setHasWithdrawingAccount(String hasWithdrawingAccount) {
    this.hasWithdrawingAccount = hasWithdrawingAccount;
  }

  /**
   * 是否已签到 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否已签到 - 0为否 1为是")
  public String getHasSignedIn() {
    return hasSignedIn;
  }
  public void setHasSignedIn(String hasSignedIn) {
    this.hasSignedIn = hasSignedIn;
  }

  /**
   * 是否有新消息 - 0为否 1为是
   **/
  @ApiModelProperty(value = "是否有新消息 - 0为否 1为是")
  public String getHasNewMsg() {
    return hasNewMsg;
  }
  public void setHasNewMsg(String hasNewMsg) {
    this.hasNewMsg = hasNewMsg;
  }

  /**
   * 新消息数
   **/
  @ApiModelProperty(value = "新消息数")
  public String getNewMsgsCount() {
    return newMsgsCount;
  }
  public void setNewMsgsCount(String newMsgsCount) {
    this.newMsgsCount = newMsgsCount;
  }

  /**
   * 获得赞数
   **/
  @ApiModelProperty(value = "获得赞数")
  public String getPraiseCount() {
    return praiseCount;
  }
  public void setPraiseCount(String praiseCount) {
    this.praiseCount = praiseCount;
  }

  /**
   * 金币数（数值）
   **/
  @ApiModelProperty(value = "金币数（数值）")
  public String getGoldsCount() {
    return goldsCount;
  }
  public void setGoldsCount(String goldsCount) {
    this.goldsCount = goldsCount;
  }

  /**
   * 积分（数值）
   **/
  @ApiModelProperty(value = "积分（数值）")
  public String getPointsCount() {
    return pointsCount;
  }
  public void setPointsCount(String pointsCount) {
    this.pointsCount = pointsCount;
  }

  /**
   * 是否是VIP用户
   **/
  @ApiModelProperty(value = "是否是VIP用户")
  public String getIsVip() {
    return isVip;
  }
  public void setIsVip(String isVip) {
    this.isVip = isVip;
  }

  /**
   * VIP专享权益链接
   **/
  @ApiModelProperty(value = "VIP专享权益链接")
  public String getVipExclusiveItemsUrl() {
    return vipExclusiveItemsUrl;
  }
  public void setVipExclusiveItemsUrl(String vipExclusiveItemsUrl) {
    this.vipExclusiveItemsUrl = vipExclusiveItemsUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UserInfoModelRegion getRegion() {
    return region;
  }
  public void setRegion(UserInfoModelRegion region) {
    this.region = region;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfoModel userInfoModel = (UserInfoModel) o;
    return (uid == null ? userInfoModel.uid == null : uid.equals(userInfoModel.uid)) &&
        (username == null ? userInfoModel.username == null : username.equals(userInfoModel.username)) &&
        (avatar == null ? userInfoModel.avatar == null : avatar.equals(userInfoModel.avatar)) &&
        (userLevel == null ? userInfoModel.userLevel == null : userLevel.equals(userInfoModel.userLevel)) &&
        (groupName == null ? userInfoModel.groupName == null : groupName.equals(userInfoModel.groupName)) &&
        (sex == null ? userInfoModel.sex == null : sex.equals(userInfoModel.sex)) &&
        (signature == null ? userInfoModel.signature == null : signature.equals(userInfoModel.signature)) &&
        (areaCode == null ? userInfoModel.areaCode == null : areaCode.equals(userInfoModel.areaCode)) &&
        (phoneNumber == null ? userInfoModel.phoneNumber == null : phoneNumber.equals(userInfoModel.phoneNumber)) &&
        (hiddenPartsPhoneNumber == null ? userInfoModel.hiddenPartsPhoneNumber == null : hiddenPartsPhoneNumber.equals(userInfoModel.hiddenPartsPhoneNumber)) &&
        (mail == null ? userInfoModel.mail == null : mail.equals(userInfoModel.mail)) &&
        (privilegeUrl == null ? userInfoModel.privilegeUrl == null : privilegeUrl.equals(userInfoModel.privilegeUrl)) &&
        (balance == null ? userInfoModel.balance == null : balance.equals(userInfoModel.balance)) &&
        (freezedBalance == null ? userInfoModel.freezedBalance == null : freezedBalance.equals(userInfoModel.freezedBalance)) &&
        (balanceView == null ? userInfoModel.balanceView == null : balanceView.equals(userInfoModel.balanceView)) &&
        (freezedBalanceView == null ? userInfoModel.freezedBalanceView == null : freezedBalanceView.equals(userInfoModel.freezedBalanceView)) &&
        (phoneNumberIsUnique == null ? userInfoModel.phoneNumberIsUnique == null : phoneNumberIsUnique.equals(userInfoModel.phoneNumberIsUnique)) &&
        (hasBindedPhoneNumber == null ? userInfoModel.hasBindedPhoneNumber == null : hasBindedPhoneNumber.equals(userInfoModel.hasBindedPhoneNumber)) &&
        (hasSettedWithdrawingPwd == null ? userInfoModel.hasSettedWithdrawingPwd == null : hasSettedWithdrawingPwd.equals(userInfoModel.hasSettedWithdrawingPwd)) &&
        (hasWithdrawingAccount == null ? userInfoModel.hasWithdrawingAccount == null : hasWithdrawingAccount.equals(userInfoModel.hasWithdrawingAccount)) &&
        (hasSignedIn == null ? userInfoModel.hasSignedIn == null : hasSignedIn.equals(userInfoModel.hasSignedIn)) &&
        (hasNewMsg == null ? userInfoModel.hasNewMsg == null : hasNewMsg.equals(userInfoModel.hasNewMsg)) &&
        (newMsgsCount == null ? userInfoModel.newMsgsCount == null : newMsgsCount.equals(userInfoModel.newMsgsCount)) &&
        (praiseCount == null ? userInfoModel.praiseCount == null : praiseCount.equals(userInfoModel.praiseCount)) &&
        (goldsCount == null ? userInfoModel.goldsCount == null : goldsCount.equals(userInfoModel.goldsCount)) &&
        (pointsCount == null ? userInfoModel.pointsCount == null : pointsCount.equals(userInfoModel.pointsCount)) &&
        (isVip == null ? userInfoModel.isVip == null : isVip.equals(userInfoModel.isVip)) &&
        (vipExclusiveItemsUrl == null ? userInfoModel.vipExclusiveItemsUrl == null : vipExclusiveItemsUrl.equals(userInfoModel.vipExclusiveItemsUrl)) &&
        (region == null ? userInfoModel.region == null : region.equals(userInfoModel.region));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (uid == null ? 0: uid.hashCode());
    result = 31 * result + (username == null ? 0: username.hashCode());
    result = 31 * result + (avatar == null ? 0: avatar.hashCode());
    result = 31 * result + (userLevel == null ? 0: userLevel.hashCode());
    result = 31 * result + (groupName == null ? 0: groupName.hashCode());
    result = 31 * result + (sex == null ? 0: sex.hashCode());
    result = 31 * result + (signature == null ? 0: signature.hashCode());
    result = 31 * result + (areaCode == null ? 0: areaCode.hashCode());
    result = 31 * result + (phoneNumber == null ? 0: phoneNumber.hashCode());
    result = 31 * result + (hiddenPartsPhoneNumber == null ? 0: hiddenPartsPhoneNumber.hashCode());
    result = 31 * result + (mail == null ? 0: mail.hashCode());
    result = 31 * result + (privilegeUrl == null ? 0: privilegeUrl.hashCode());
    result = 31 * result + (balance == null ? 0: balance.hashCode());
    result = 31 * result + (freezedBalance == null ? 0: freezedBalance.hashCode());
    result = 31 * result + (balanceView == null ? 0: balanceView.hashCode());
    result = 31 * result + (freezedBalanceView == null ? 0: freezedBalanceView.hashCode());
    result = 31 * result + (phoneNumberIsUnique == null ? 0: phoneNumberIsUnique.hashCode());
    result = 31 * result + (hasBindedPhoneNumber == null ? 0: hasBindedPhoneNumber.hashCode());
    result = 31 * result + (hasSettedWithdrawingPwd == null ? 0: hasSettedWithdrawingPwd.hashCode());
    result = 31 * result + (hasWithdrawingAccount == null ? 0: hasWithdrawingAccount.hashCode());
    result = 31 * result + (hasSignedIn == null ? 0: hasSignedIn.hashCode());
    result = 31 * result + (hasNewMsg == null ? 0: hasNewMsg.hashCode());
    result = 31 * result + (newMsgsCount == null ? 0: newMsgsCount.hashCode());
    result = 31 * result + (praiseCount == null ? 0: praiseCount.hashCode());
    result = 31 * result + (goldsCount == null ? 0: goldsCount.hashCode());
    result = 31 * result + (pointsCount == null ? 0: pointsCount.hashCode());
    result = 31 * result + (isVip == null ? 0: isVip.hashCode());
    result = 31 * result + (vipExclusiveItemsUrl == null ? 0: vipExclusiveItemsUrl.hashCode());
    result = 31 * result + (region == null ? 0: region.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfoModel {\n");
    
    sb.append("  uid: ").append(uid).append("\n");
    sb.append("  username: ").append(username).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  userLevel: ").append(userLevel).append("\n");
    sb.append("  groupName: ").append(groupName).append("\n");
    sb.append("  sex: ").append(sex).append("\n");
    sb.append("  signature: ").append(signature).append("\n");
    sb.append("  areaCode: ").append(areaCode).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  hiddenPartsPhoneNumber: ").append(hiddenPartsPhoneNumber).append("\n");
    sb.append("  mail: ").append(mail).append("\n");
    sb.append("  privilegeUrl: ").append(privilegeUrl).append("\n");
    sb.append("  balance: ").append(balance).append("\n");
    sb.append("  freezedBalance: ").append(freezedBalance).append("\n");
    sb.append("  balanceView: ").append(balanceView).append("\n");
    sb.append("  freezedBalanceView: ").append(freezedBalanceView).append("\n");
    sb.append("  phoneNumberIsUnique: ").append(phoneNumberIsUnique).append("\n");
    sb.append("  hasBindedPhoneNumber: ").append(hasBindedPhoneNumber).append("\n");
    sb.append("  hasSettedWithdrawingPwd: ").append(hasSettedWithdrawingPwd).append("\n");
    sb.append("  hasWithdrawingAccount: ").append(hasWithdrawingAccount).append("\n");
    sb.append("  hasSignedIn: ").append(hasSignedIn).append("\n");
    sb.append("  hasNewMsg: ").append(hasNewMsg).append("\n");
    sb.append("  newMsgsCount: ").append(newMsgsCount).append("\n");
    sb.append("  praiseCount: ").append(praiseCount).append("\n");
    sb.append("  goldsCount: ").append(goldsCount).append("\n");
    sb.append("  pointsCount: ").append(pointsCount).append("\n");
    sb.append("  isVip: ").append(isVip).append("\n");
    sb.append("  vipExclusiveItemsUrl: ").append(vipExclusiveItemsUrl).append("\n");
    sb.append("  region: ").append(region).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
