/**
 * 五五海淘返利APP新版接口
 * 更新日志<br> 相对于上一build的变更： <br/>Nu 调整搜索模型 
 *
 * OpenAPI spec version: 1.8 build20180202-2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class VipRebateStoreModel  {
  
  @SerializedName("store_id")
  private String storeId = null;
  @SerializedName("store_name")
  private String storeName = null;
  @SerializedName("store_logo")
  private String storeLogo = null;
  @SerializedName("country_flag_pic")
  private String countryFlagPic = null;
  @SerializedName("category_name")
  private String categoryName = null;
  @SerializedName("user_has_rebate")
  private String userHasRebate = null;
  @SerializedName("rebate_view")
  private String rebateView = null;
  @SerializedName("vip_rebate_view")
  private String vipRebateView = null;
  @SerializedName("orders_count")
  private String ordersCount = null;
  @SerializedName("collections_count")
  private String collectionsCount = null;

  /**
   * 商家id
   **/
  @ApiModelProperty(value = "商家id")
  public String getStoreId() {
    return storeId;
  }
  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  /**
   * 商家名称
   **/
  @ApiModelProperty(value = "商家名称")
  public String getStoreName() {
    return storeName;
  }
  public void setStoreName(String storeName) {
    this.storeName = storeName;
  }

  /**
   * 商家图标
   **/
  @ApiModelProperty(value = "商家图标")
  public String getStoreLogo() {
    return storeLogo;
  }
  public void setStoreLogo(String storeLogo) {
    this.storeLogo = storeLogo;
  }

  /**
   * 国旗图标
   **/
  @ApiModelProperty(value = "国旗图标")
  public String getCountryFlagPic() {
    return countryFlagPic;
  }
  public void setCountryFlagPic(String countryFlagPic) {
    this.countryFlagPic = countryFlagPic;
  }

  /**
   * 商家类别
   **/
  @ApiModelProperty(value = "商家类别")
  public String getCategoryName() {
    return categoryName;
  }
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * 普通用户是否有返利
   **/
  @ApiModelProperty(value = "普通用户是否有返利")
  public String getUserHasRebate() {
    return userHasRebate;
  }
  public void setUserHasRebate(String userHasRebate) {
    this.userHasRebate = userHasRebate;
  }

  /**
   * 返利比率（文字说明）
   **/
  @ApiModelProperty(value = "返利比率（文字说明）")
  public String getRebateView() {
    return rebateView;
  }
  public void setRebateView(String rebateView) {
    this.rebateView = rebateView;
  }

  /**
   * vip返利比率（文字说明）
   **/
  @ApiModelProperty(value = "vip返利比率（文字说明）")
  public String getVipRebateView() {
    return vipRebateView;
  }
  public void setVipRebateView(String vipRebateView) {
    this.vipRebateView = vipRebateView;
  }

  /**
   * 成功下单数
   **/
  @ApiModelProperty(value = "成功下单数")
  public String getOrdersCount() {
    return ordersCount;
  }
  public void setOrdersCount(String ordersCount) {
    this.ordersCount = ordersCount;
  }

  /**
   * 收藏数
   **/
  @ApiModelProperty(value = "收藏数")
  public String getCollectionsCount() {
    return collectionsCount;
  }
  public void setCollectionsCount(String collectionsCount) {
    this.collectionsCount = collectionsCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VipRebateStoreModel vipRebateStoreModel = (VipRebateStoreModel) o;
    return (storeId == null ? vipRebateStoreModel.storeId == null : storeId.equals(vipRebateStoreModel.storeId)) &&
        (storeName == null ? vipRebateStoreModel.storeName == null : storeName.equals(vipRebateStoreModel.storeName)) &&
        (storeLogo == null ? vipRebateStoreModel.storeLogo == null : storeLogo.equals(vipRebateStoreModel.storeLogo)) &&
        (countryFlagPic == null ? vipRebateStoreModel.countryFlagPic == null : countryFlagPic.equals(vipRebateStoreModel.countryFlagPic)) &&
        (categoryName == null ? vipRebateStoreModel.categoryName == null : categoryName.equals(vipRebateStoreModel.categoryName)) &&
        (userHasRebate == null ? vipRebateStoreModel.userHasRebate == null : userHasRebate.equals(vipRebateStoreModel.userHasRebate)) &&
        (rebateView == null ? vipRebateStoreModel.rebateView == null : rebateView.equals(vipRebateStoreModel.rebateView)) &&
        (vipRebateView == null ? vipRebateStoreModel.vipRebateView == null : vipRebateView.equals(vipRebateStoreModel.vipRebateView)) &&
        (ordersCount == null ? vipRebateStoreModel.ordersCount == null : ordersCount.equals(vipRebateStoreModel.ordersCount)) &&
        (collectionsCount == null ? vipRebateStoreModel.collectionsCount == null : collectionsCount.equals(vipRebateStoreModel.collectionsCount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (storeId == null ? 0: storeId.hashCode());
    result = 31 * result + (storeName == null ? 0: storeName.hashCode());
    result = 31 * result + (storeLogo == null ? 0: storeLogo.hashCode());
    result = 31 * result + (countryFlagPic == null ? 0: countryFlagPic.hashCode());
    result = 31 * result + (categoryName == null ? 0: categoryName.hashCode());
    result = 31 * result + (userHasRebate == null ? 0: userHasRebate.hashCode());
    result = 31 * result + (rebateView == null ? 0: rebateView.hashCode());
    result = 31 * result + (vipRebateView == null ? 0: vipRebateView.hashCode());
    result = 31 * result + (ordersCount == null ? 0: ordersCount.hashCode());
    result = 31 * result + (collectionsCount == null ? 0: collectionsCount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VipRebateStoreModel {\n");
    
    sb.append("  storeId: ").append(storeId).append("\n");
    sb.append("  storeName: ").append(storeName).append("\n");
    sb.append("  storeLogo: ").append(storeLogo).append("\n");
    sb.append("  countryFlagPic: ").append(countryFlagPic).append("\n");
    sb.append("  categoryName: ").append(categoryName).append("\n");
    sb.append("  userHasRebate: ").append(userHasRebate).append("\n");
    sb.append("  rebateView: ").append(rebateView).append("\n");
    sb.append("  vipRebateView: ").append(vipRebateView).append("\n");
    sb.append("  ordersCount: ").append(ordersCount).append("\n");
    sb.append("  collectionsCount: ").append(collectionsCount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
